### ISSUE TITLE
Feature was slow to generate! (2512ms): []

### ISSUE THREAD

**Issue by s10w10rr1s** [TerraForged/tracker#100]
Horrible chinese water torture-esque seize ups. Getting hit with 2-3 second freezes whenever I am generating chunks "[TerraForged/]: Feature was slow to generate! (2512ms): []". 
Refuses to identify what it is trying to generate. Absolutely maddening.
[debug.log](https://github.com/TerraForged/tracker/files/6370515/debug.log)
[debug-1.log.gz](https://github.com/TerraForged/tracker/files/6370516/debug-1.log.gz)
[latest.log](https://github.com/TerraForged/tracker/files/6370517/latest.log)
[2021-04-24-1.log.gz](https://github.com/TerraForged/tracker/files/6370518/2021-04-24-1.log.gz)
Is the issue that this mod is delicate and combative with other mods? Are there known incompatibilities?

**Comment by Won-Ton** [comment]
It's caused by one of your other mods that has added some poorly optimized worldgen feature(s).
You'll need to do your own investigation to figure out which one is the issue
