### ISSUE TITLE
NullPointerException Server Crash - Generating Structure Village

### ISSUE THREAD

**Issue by Yourname942** [TerraForged/tracker#101]
**PLEASE PROVIDE DETAILED INFORMATION, LOGS, CRASH-REPORTS.**  
[Search for existing issues before opening a new one.](https://github.com/TerraForged/tracker/issues?q=)  
_Note: we are not accepting feature requests/questions. Just bugs pls :]_

Minecraft 1.16.5
Forge 36.1.2
TerraForged 0.2.10

I was just flying around while in creative mode to explore the world, then the server crashed.

crash log:
https://gist.github.com/Yourname942/e6c096a54ec27a35a4cb5338612a59a3

latest log:
https://gist.github.com/Yourname942/0945d26b2d0b785e1b2913331526b963

debug log:
https://gist.github.com/Yourname942/a1867bcf73fec44f430343dc914eedd6

**Comment by Won-Ton** [comment]
This isn't caused by TF. The crash is propagating from the greekfantasy mod.
