### ISSUE TITLE
Biomes from Twist do not generate

### ISSUE THREAD

**Issue by TheQKnight** [TerraForged/tracker#102]
Minecraft: 1.16.5
Forge: 36.1.13
Twist: 1.3.3
Terraforged: 0.2.10

Biomes from Twist do not generate in Terraforged worlds.

**Comment by Won-Ton** [comment]
Information about what TF needs from third party mods to find their biomes here:
<https://github.com/TerraForged/TerraForged/wiki/Mod:-Biomes>
