### ISSUE TITLE
Biomes You Go Biomes Not Generating Properly 

### ISSUE THREAD

**Issue by Yourname942** [TerraForged/tracker#103]
**PLEASE PROVIDE DETAILED INFORMATION, LOGS, CRASH-REPORTS.**  
[Search for existing issues before opening a new one.](https://github.com/TerraForged/tracker/issues?q=)  
_Note: we are not accepting feature requests/questions. Just bugs pls :]_
Minecraft 1.16.5
Forge 36.1.2
Terraforged 0.2.10
Biomes You Go 1.2

Terraforged does not work well with Biomes You Go. These biomes are not properly generating:
Polluted lake, sierra range, red rock lowlands and fresh water lake

Steps to Reproduce:
Select Beautiful
Change some sliders
Save as default (and as a preset)
copy/paste the preset and paste into the server config
set server properties' level-type=terraforged:terraforged
launch server
launch client
join world
fly around in creative

Note I have Biomes O Plenty, Autumnity, Environmental, and several other mods which add biomes to the overworld.

Modlist: https://gist.github.com/Yourname942/6812b9b08c375e020d19fa32a6187c6f

![2021-04-30_14 37 38](https://user-images.githubusercontent.com/58750222/116759600-b3d85600-a9e0-11eb-885e-d5d779d50edd.jpg)

**Comment by Won-Ton** [comment]
we cant do anything about biomes that are too heavily dependant on the vanilla chunk generator
