### ISSUE TITLE
Crash when going onto the Create World screen (possibly something gone wrong with my custom preset)

### ISSUE THREAD

**Issue by pm065** [TerraForged/tracker#104]
Since I added a bunch of new mods to my pack, I decided to delete the old testing worlds, which were the only ones I had, but as soon as I deleted the last one, the game crashed. Clicking Single Player again causes the crash again. The crash report claims TerraForged is the culprit.
Full log: https://paste.ubuntu.com/p/Gr548vjrgr/
Crash report: https://paste.ubuntu.com/p/CDzND82T3r/

**Comment by pm065** [comment]
It seems like the culprit is the whole Create World screen; when I tried using a world from a different instance as a 'dummy', it still crashed when I tried to create another new world...

**Comment by pm065** [comment]
Changing the Forge Default World Type back to default allowed me to get onto Create World, but as soon as I switched the world type to TerraForged it crashed again.

**Comment by pm065** [comment]
Alright, so there's something wrong with my preset. I'll try remaking it. Here it is, by the way: https://paste.ubuntu.com/p/tv4qJ8rxxG/

**Comment by Won-Ton** [comment]
It's not clear what's going on tbh. The crash report is saying it's related to structures but I can't think off think off the top of my head what a mod could be doing to cause this part of the code to trip up.

I've seen mods configure their structures with invalid seeds which could lead to a crash here, but that usually prints a specific message.

I'll leave this open for a little while and if you can recreate with just TF + forge look further into it.

**Comment by pm065** [comment]
Deleting and remaking my custom preset stopped the issue.  Since I deleted my preset, I don't think I'll be able to reproduce it. I'll reopen the issue if the problem comes back.

**Comment by pm065** [comment]
It happened again with the same crash...

**Comment by Won-Ton** [comment]
You'll need to investigate what mod's structure is causing the issue. If you can recreate the problem with just TF installed feel free to open a new ticket with the crash report + logs for that

**Comment by pm065** [comment]
Turns out it was a false alarm anyway, my old preset had somehow wormed its way back into the presets folder via GitHub (I'm attempting to build a modpack, and I just recently decided to put it on a private GitHub repo)
