### ISSUE TITLE
Terraforged Missing Structure Options

### ISSUE THREAD

**Issue by Yourname942** [TerraForged/tracker#105]
**PLEASE PROVIDE DETAILED INFORMATION, LOGS, CRASH-REPORTS.**  
[Search for existing issues before opening a new one.](https://github.com/TerraForged/tracker/issues?q=)  
_Note: we are not accepting feature requests/questions. Just bugs pls :]_

Configurations Missing in Terraforged:

1) Apotheosis Tome towers (it is configured in their deadly module)
```
   # The 1/n chance (per chunk) that a tome tower may attempt generation. 0 = disabled, lower = more chances. [range: 0 ~ 50000, default: 125]
    I:"Tome Tower"=125
```
![2021-04-30_14 40 34](https://user-images.githubusercontent.com/58750222/116829394-ce8e0480-ab71-11eb-824c-ab4970094d30.png)
    
2) Farlanders Obsidian Spires
```
    #Obsidian Spire rarity (higher number = lower spawnrate)
	obsidianSpireSpawnRate = 3
```
![1](https://user-images.githubusercontent.com/58750222/116830358-71954d00-ab77-11eb-822e-f96f20d78914.jpg)

Please add these structures to the list of configurable structures, so that we can space them out how far we need them to be. Thank you.

**Comment by Won-Ton** [comment]
It's up to the mod to register their structures settings in a way TF can discover and use them
