### ISSUE TITLE
Enhanced Mushrooms not generating despite making a datapack

### ISSUE THREAD

**Issue by MilkMan1776** [TerraForged/tracker#106]
**PLEASE PROVIDE DETAILED INFORMATION, LOGS, CRASH-REPORTS.**  
[Search for existing issues before opening a new one.](https://github.com/TerraForged/tracker/issues?q=)  
_Note: we are not accepting feature requests/questions. Just bugs pls :]_

I've tried making a data pack that would allow enhanced mushrooms to generate properly. Despite my best effort I just can't figure it out. I was hoping sometime in the future you could either make a compat patch or a datapack.

**Comment by Won-Ton** [comment]
Sorry no we don't write mod-specific compat stuff. Datapack overrides are mojang's system so they should be the ones providing support for it for end users such as yourself
