### ISSUE TITLE
Bee nests DO NOT generate

### ISSUE THREAD

**Issue by MilkMan1776** [TerraForged/tracker#108]
All threads were made while using version 0.2.9

I've planted well over 1000 trees, a mix of oak and birch. And a mix of flowers. Not a single bee nest.
Like with enhanced mushrooms, bee nests do not generate naturally with enhanced biome features turned on.

**Comment by Won-Ton** [comment]
Has been discussed on discord. the nests do generate naturally. spawn rates can be overriden by json files contained in the jar
