### ISSUE TITLE
BGcore cave biomes not integrated

### ISSUE THREAD

**Issue by StrangerSon713** [TerraForged/tracker#113]
@ItsBlackGear Has a integration API, and I believe that your BiomeProvider doesn't include any of the cave biomes from its dependents.

**Comment by ItsBlackGear** [comment]
umm ok, i understand that you want cave biomes but you just made a duplication of a previous issue that you opened.

i'm currently turning bgcore into a cave biome api only, i already have it documented but i'm still working on that

**Comment by Won-Ton** [comment]
Cave biomes are coming in 1.17/.18 and we'll put resources into encorporating them when that happens. We have no plans to add dependency on third party libs. Perhaps you can find someone to write an add-on that bridges the two mods.
