### ISSUE TITLE
Crash on making new world

### ISSUE THREAD

**Issue by Moobien** [TerraForged/tracker#114]
**PLEASE PROVIDE DETAILED INFORMATION, LOGS, CRASH-REPORTS.**  
[Search for existing issues before opening a new one.](https://github.com/TerraForged/tracker/issues?q=)  
_Note: we are not accepting feature requests/questions. Just bugs pls :]_

Hey guys, running Terraforged TerraForged-1.16.5-0.2.10 and when I tried to make a new world, I got the following crash. clicked fine through all the world types until it got to terraforged.

https://gist.github.com/Moobien/1d552d094a52bbdf61a344a7a6a4017f

**Comment by Won-Ton** [comment]
Please search for similar issues before opening new ones

**Comment by Moobien** [comment]
I saw no open issues hence why I opened this one
