### ISSUE TITLE
Crash while generating a structure :/

### ISSUE THREAD

**Issue by emanuele246gi** [TerraForged/tracker#115]
This is the crash report: 

https://pastebin.com/MsZr4dEe

Inside the text there should also be the Minecraft, Forge and Terraforged versions

**Comment by Won-Ton** [comment]
It's an problem with the structure that was generating: `minecraft:titan_spire`

**Comment by emanuele246gi** [comment]
You don't say... I can read -_-, anyway I wanted to know how I could possibly fix it

**Comment by Won-Ton** [comment]
go ask the mod that adds that structure maybe?
