### ISSUE TITLE
Terraforged and dimension mod compatibility.

### ISSUE THREAD

**Issue by aWhisper20** [TerraForged/tracker#118]
When attempting to enter SOME alternate dimension mods such as twilight forest or the undergarden in a terraforged world, the terrain in the alternate biome is just an empty wasteland almost like a superflat world (Most dimensions work fine). Note that this only happens if the world is a terraforged world (i.e. if I make a default world then the alternate dimension terrain is just fine). Pictures attached of bug in action (I have night vision on to make it easier to see).

Twilight forest:
![image](https://user-images.githubusercontent.com/84068550/119300778-f0d1ea00-bc26-11eb-9917-4495de0fc7f8.png)

Undergarden:
![image](https://user-images.githubusercontent.com/84068550/119300884-22e34c00-bc27-11eb-8169-897e0d91e1ed.png)

**Comment by Won-Ton** [comment]
I'm not getting this issue testing both dimenions from the latest version of twightlight forest with the latest of terraforged when terraforged is handling the overworld.

TerraForged shouldn't have any effect on other dimensions other than overworld. If you have other mods installed it could well be something to do with them. Keep in mind also that twi-fo is in beta status so it could just be a bug there.

If you can recreate the issue with just TerraForged and twi-fo installed feel free to come back and let me know how to reproduce.

**Comment by aWhisper20** [comment]
Solved it! turns out the mod "More waterlogging" was causing the issue with the modded dimensions. Sorry for falsely accusing terraforged, it was just the only worldgen mod so my mind went to that first. Have a good day!
