### ISSUE TITLE
Structure options are missing from the ui after loading a preset with disabled structures (ie can't reenable them!)

### ISSUE THREAD

**Issue by cosmicdan** [TerraForged/tracker#119]
Howdy,

In the latest 1.16.5 release, upon saving a preset, any structure that was set to disabled = true will be simply skipped over in the config (erased from the file).

Upon loading that preset again, the settings for those structures are back at their default in the config.

Thus, it is not possible to save a preset where any structure generation is disabled.

Thank you!

**Comment by Won-Ton** [comment]
You need to press the 'load' button after selecting the preset to load its settings.

However, in testing; when you load a preset that has disabled structures in it those disabled structures no longer appear in the ui so you can't reenable them, which _is_ a problem that needs fixing

**Comment by cosmicdan** [comment]
Loading presets is fine, what happens is once you set disabled = true for a structure and then save that preset, those disabled structures are completely absent in the preset file. That's why they're missing in the UI after loading.

BUT, if you go and load that preset again after a new MC startup, it will put them back with the default/initial values.

I wouldn't have noticed if I didn't track my Configs under a git repo - I kept seeing disabled structures disappear and reappear in the saved preset.

⁣Get BlueMail for Android ​

**Comment by Won-Ton** [comment]
Yeah the whole thing is a bit wonky the more I look at it. That's entirely my bad. I'll try get it behaving a bit more predictably

**Comment by Won-Ton** [comment]
please try version 0.2.11
