### ISSUE TITLE
New version of TerraForged-1.16.4-0.2.2-RC-2.jar has changed the seed generation....

### ISSUE THREAD

**Issue by TheOrionsun** [TerraForged/tracker#12]
Hello,

Just for you information....

MC-1.16.4
Forge-35.1.36

New version of TerraForged-1.16.4-0.2.2-RC-2.jar has changed the seed generation. In older version generated world where there was land generated there is now an ocean where the entire land mass was.

I just trimmed new areas and loaded previous version of TF to fix.

Thank you for your great Mod!,

Orion

**Comment by Won-Ton** [comment]
yep
