### ISSUE TITLE
Datapack biomes

### ISSUE THREAD

**Issue by theboo** [TerraForged/tracker#121]
Hello!! I have a question nd maybe a bug but not sure..

Does TF support datapack biomes from mods? for whatever reason the ars nouveau archwood forest wont show up in terraforged worlds. It shows up in the biome weights dump but not the biome map. They made the biome using a datapack, and it has the same temp/downfall/category as a vanilla forest. Shows up fine in default world type worlds
https://github.com/baileyholl/Ars-Nouveau/blob/8d8961c4ccbc830b8fb45da0737b7b286c4ba978/src/main/resources/data/ars_nouveau/worldgen/biome/archwood_forest.json
https://github.com/baileyholl/Ars-Nouveau/blob/8d8961c4ccbc830b8fb45da0737b7b286c4ba978/src/main/java/com/hollingsworth/arsnouveau/common/event/WorldEvent.java
I also manually added it to the biome_weights.conf in config, but when i do a dump it does not show the weights i gave it as it does with other biomes, it shows as the default weight.

We have a few other mods that add biomes but this is the only one i cant get to show up, and i believe it is the only one that was created using a datapack.

**Comment by Won-Ton** [comment]
Hi! Same as regular biomes; if they have the overworld biome dictionary tag then TF will try to use them:
https://github.com/TerraForged/TerraForged/wiki/Mod:-Biomes

**Comment by theboo** [comment]
Ah ha, so corgi was right in discord and it's just missing the overworld tag... Also explains why the weights dont register... I'll let bailey know, thanks!

**Comment by theboo** [comment]
closing this as no overworld dictionary tag is definitely the issue... thanks for the info!!
