### ISSUE TITLE
Mana and Artifice Compatibility

### ISSUE THREAD

**Issue by Liamdude** [TerraForged/tracker#123]
This issue has been raised both here and on the Mana and Artifice Github, but structures in Mana and Artifice do not spawn in worlds using TerraForged. Currently, M&A's developer, Mithion, is seeking information from the TerraForged developers to figure out how to make these mods compatible.

The relevant issues are below: 
https://github.com/Mithion/Mana-And-Artifice/issues/218 (this one is where Mithion is asking for help)
https://github.com/Mithion/Mana-And-Artifice/issues/169
https://github.com/TerraForged/tracker/issues/74 (similar to prior issue report but posted to this tracker)

**Comment by Won-Ton** [comment]
We have a page here:
https://github.com/TerraForged/TerraForged/wiki/Mod:-Structures:-Compatibility

I can't really do any investigation on our end as that mod does not publish their source code :/
