### ISSUE TITLE
LOTR mod

### ISSUE THREAD

**Issue by TackleToWin** [TerraForged/tracker#124]
Good Afternoon, today was trying to load a map with Terraforged as level type and then I got this error, I'm not exactly sure if this is a LOTR side error or Terraforged so I will be sending this to both. This is LOTR Renewed 4.1, Terraforged 0.2.10, Forge 36.1.24

https://pastebin.com/mMN2tGrg

**Comment by Won-Ton** [comment]
Isn't caused by TF
