### ISSUE TITLE
Crash when encountering structures during generation

### ISSUE THREAD

**Issue by NillerMedDild** [TerraForged/tracker#128]
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/2436
Also reported here: https://github.com/ValhelsiaTeam/Valhelsia-Structures/issues/82

While pre-generating our server world it encountered some kind of Tetra and Valhelsia structure which causes a hard crash as soon as it loaded those chunks. I haven't yet tested if manually going into those chunks will have the same effect.

### Versions
- Forge-1.16.5-36.1.31
- valhelsia_structures-1.16.5-0.1.2
- TerraForged-1.16.5-0.2.10

**Comment by Won-Ton** [comment]
Hi. It's propagating from feature `[tetra:feature]`. Looks like it's trying to place one of Valhesia Structure's blocks (DungeonDoorBlock) during feature/structure generation, and part of that block's code is not safe to call within this part of chunk generation causing the `ClassCastException` which is blowing everything up.

**Comment by NillerMedDild** [comment]
Alright, thanks a bunch 👍
