### ISSUE TITLE
Stone options

### ISSUE THREAD

**Issue by thedeerirty** [TerraForged/tracker#129]
Question; is there a way to blacklist specific blocks or stone types from being apart of mountain generation? For example, Create adds stone types that generate as stone naturally, but because of that are often apart of cliffs and such when playing with terraforged.

**Comment by Won-Ton** [comment]
Yep you can create a datapack to override the `forge:wg_stone` block tag using `"replace": true` that contains only the blocks you want to appear.

If that's too much work you can just disable the 'strata decorator' stone will generate more like vanilla where it's mostly plain stone and other stone types generate in blobs
