### ISSUE TITLE
Village Generation error on server

### ISSUE THREAD

**Issue by thedeerirty** [TerraForged/tracker#130]
![error2](https://user-images.githubusercontent.com/58305182/122858992-44e4f280-d2e9-11eb-83b4-a9806ea4f9ad.PNG)

My server's getting spammed with this occasionally. I can grab a log too, but I'm concerned at how this issues happening. Causing a lot of lag when breaking blocks.

**Comment by Won-Ton** [comment]
I would need to see the full log
