### ISSUE TITLE
missing make defaults or "set defaults" (missing docs)

### ISSUE THREAD

**Issue by k1r0s** [TerraForged/tracker#135]
I want to create a world on a forge server but i want to be able to change generator settings

By following the steps defined below I found an issues.
https://github.com/TerraForged/community/wiki/Forger-Server:-Advanced

There is no "make defaults" regarding mod configuration. 

However by clicking on "edit" from the singleplayer menu we can see an option "export generator settigns" but it does not work as expected.

What is the updated way to do this?

**Comment by Won-Ton** [comment]
https://github.com/TerraForged/TerraForged/wiki/User:-Server:-Setup
