### ISSUE TITLE
[Feature Request] Visual indicator for seed spawn point

### ISSUE THREAD

**Issue by AngleWyrm10** [TerraForged/tracker#136]
Put crosshairs in the center of the map where the spawn point will be
![Untitled](https://user-images.githubusercontent.com/55937426/125714975-5c0d816b-dfb4-45a8-ade3-e5174dfb4bba.png)

**Comment by Won-Ton** [comment]
It's roughly the center of the image. Minecraft fuzzes the actual position you spawn at
