### ISSUE TITLE
[crash] when moving around/worldgen in overworld with dynamic trees

### ISSUE THREAD

**Issue by Seth0067** [TerraForged/tracker#137]
[crash report paste](https://pastebin.com/6diCtEJW)
[latest log paste](https://pastebin.com/vrw1Qcub)

Hey - this was a server crash when roaming the overworld. Looks Dynamic Trees related but noticed a note on an issue there that may be related. 

Can you let me know what you think?

**Comment by Won-Ton** [comment]
Hi from the log there seems to be something going wrong with dynamic trees. Whether it's a bug on their end or another mod is conflicting with it I'm not sure sorry.

(The crash-report you've provided is not from the same session that the log was recorded btw. In the crash-report it doesn't look like TF was even active as the chunk generator)

**Comment by Seth0067** [comment]
ok noted - ill throw it over to them. thanks for your attention
