### ISSUE TITLE
[1.16.5] Crash with Forestry

### ISSUE THREAD

**Issue by Liamdude** [TerraForged/tracker#139]
I have experienced some random crashes that occur *sometimes* when Terraforged and Forestry are used together. There never seems to be a reason based on anything during playtime. Sometimes it crashes while loading, sometimes a few minutes in, and sometimes after an hour of play. From my experience during play time, the crash occurs after walking into an area where new chunks are loaded. Unfortunately, I do not really have more detailed information than that and what is available in the log files. It may also be too early to address this problem because Forestry is not officially released yet.

Forge version: 36.2.0 (I have had this occur on prior versions of Forge)
Forestry version: test-0.19 (this file comes from the Forestry Discord, but the Github is kept up to date)
Terraforged version: 0.2.13
Latest log: https://pastebin.com/HihKqCBe
Crash report: https://pastebin.com/4HB14abm

On a related note, I have also reported this issue to the Forestry developers, but I wanted to be thorough.

**Comment by Won-Ton** [comment]
Yeah this is a problem in forestry. I think theyre trying to tell the client to re-render a chunk, but doing it from inside world-gen where that chunk is currently generating?

idk, it's all a bit weird/concerning. World-gen shouldn't be interacting with clientside code like this at all. Considering it's 'test' version I imagine this is just an artifact from updating from a previous MC version or something. Pretty sure itd have issues in vanilla gen too, reporting to forestry was the right call

**Comment by Liamdude** [comment]
Thanks for the response! I will refer the developers to this and let them know that Terraforged is not the issue
