### ISSUE TITLE
[1.15] Terraforged WorldGenerator has the potential to deadlock worldgen

### ISSUE THREAD

**Issue by Speiger** [TerraForged/tracker#140]
o/ I am right now in the process of porting the new version ChunkPregenerator to 1.15-1.16.

And one of the goals was to fix any incompats that Terraforged has with Chunk Pregenerator.
It loves to get stuck with ChunkPregen. In 1.16 only but i like to investigate beforehand to see if something changed that could cause issues.

Now in 1.15 the first thing i have done (with the old logic) is setup Terraforged in my dev space (the curse release)
and run a Pregeneration with my  tool and let visual VM track everything to see if deadlocks happen or stuff like that.

And guess what:
![javaw_TWvTxDvFV8](https://user-images.githubusercontent.com/2556269/127783656-1550e94d-2857-4306-b77e-451b281cad20.png)

All  these yellow & Light Blue pieces in the WorldGen/ServerThread get stuck (its a simple terraforged worldgen no additional mods)
Yellow means the thread is awaiting something in a Synchronized block, but the light blue ones are the dangerous ones. It means the VM decided to basically monitor that thread because the potential of lock up got so high that it had to intervene at some point.

To give a example i run a non Terraforged World for comparason. (Terraforged was not in the dev space at that point afterwards)
![javaw_XulihqFYt4](https://user-images.githubusercontent.com/2556269/127783716-48ed2ca3-c8e9-430b-b20d-b1dfdd169673.png)

Not a single thread lock or waiting.

Now i have no explanation of why it happens with terraforged. I might even try your pregenerator to see if it is my tool or not but it is at least interesting to view at.

Also a side note: its nice that you want to kill threads that are not used but for debug friendlyness let them run for 5-10 seconds before they auto kill themselves. Its not hurting the PC it even optimizes code because threads don't have to be created again.

Now I am posting a "Potential" Lockup issue for 1.15 that may or may not get closed, but i can tell you already that these "maybe issues" turned most likely into an actual issue in 1.16 so having a starting point might be a good idea.

I hope I can help/find a way to solve this issue if it is a pregen issue or normal worldgen but it is interesting none the least.
Once i am done with the 1.15 port i am going to look over this again and also report on the 1.16 side of things.

Thanks for reading. Speiger

Small edit:
This is how i load Chunks with Chunk Pregenerator, its exactly the same way as MC does it just with my own Ticket:
```java
	public void startTask(long[] chunks, ChunkStatus requestedStatus, CompletableFuture<Either<IChunk, ChunkHolder.IChunkLoadingError>>[] adder)
	{
		int finalStatus = 33 + ChunkStatus.getDistance(requestedStatus);
		for(int i = 0, m = chunks.length;i < m;i++)
		{
			ChunkPos pos = new ChunkPos(chunks[i]);
			ticketing.registerWithLevel(PREGEN_TICKET, pos, finalStatus, pos);
		}
		flipChunks();
		for(int i = 0, m = chunks.length;i < m;i++)
		{
			ChunkHolder chunkholder = getHolder(provider, chunks[i]);
			if(chunkholder == null || chunkholder.getChunkLevel() > finalStatus)
			{
				throw new IllegalStateException("No chunk holder after ticket has been added");
			}
			adder[i] = chunkholder.func_219276_a(requestedStatus, manager);
		}
	}
```

**Comment by Won-Ton** [comment]
This isn't a deadlock it's just one thread waiting on another to complete which is how CompletableFutures (& vanilla's chunk provider) are designed to work. Yes it may be waiting longer with TF generating if you have it configured wrong, too few cores, too demanding settings, but it won't be left waiting indefinitely.

The 1.15 version is EOL. I never worked on myself, not familiar with what performance settings it ships with. TF 1.16 is different. We've profiled it to death and are satisfied that it performs well for the output and experience it produces.
