### ISSUE TITLE
Crash when generating Dungeon Crawl Dungeons

### ISSUE THREAD

**Issue by forebordingsky** [TerraForged/tracker#143]
It's not consistent crash, if i join game again it will probably load without crash.

[crash-2021-08-08_20.09.31-client.txt](https://github.com/TerraForged/tracker/files/6951087/crash-2021-08-08_20.09.31-client.txt)

**Comment by Won-Ton** [comment]
This isn't anything to do with TF sorry. Not even 100% sure it's in anything to do with Dungeon Call either tbh. There looks to be a bunch of mods that are coremodding vanilla code which could be causing issues for DC.
