### ISSUE TITLE
Crashing when only mod on server.  Cannot set level-type to terraforged

### ISSUE THREAD

**Issue by rchpweblo** [TerraForged/tracker#144]
[latest.log](https://github.com/TerraForged/tracker/files/6951856/latest.log)

Trying to set up a server right now
I have the most recent version of forge, and the only mod I have installed is the most recent version of terraforged
When I set level-type=terraforged the server crashes almost immediately, as you can see from the log
Terraforged is the only mod installed.  It seems to be mentioning something about biomes, but I don't understand what could be the issue when its only vanilla biomes.

**Comment by Won-Ton** [comment]
could you provide the full debug log and crash-report please

**Comment by rchpweblo** [comment]
[2021-08-08-4.log](https://github.com/TerraForged/tracker/files/6959127/2021-08-08-4.log)
[debug-5.log](https://github.com/TerraForged/tracker/files/6959128/debug-5.log)
Here you go my man

**Comment by Won-Ton** [comment]
Looks like something external of minecraft is preventing TF load data from its own jar. Make sure the file permissions set up correctly at the location you've installed your server. I suspect there's something up with your ramdisk configuration - have tried installing the server on a normal part of your harddrive?

**Comment by rchpweblo** [comment]
Noted, I'll have to take a look this Friday when I'm off of work

I'll let you know then

**Comment by rchpweblo** [comment]
Okay so I tried remaking the server in a different directory and am still having the same problem
The weirdest part of all of this is that a week before this issue happened I was running the same setup with just terraforge and was able to play and connect.  I don't know what has gone wrong.

**Comment by Won-Ton** [comment]
I'd try set it up on a different machine tbh. Preferrably not on a ramdisk too to eliminate whatever is controlling that as a factor. Redownload the jars incase they've been corrupted etc. Whatever the issue is it is external of TF
