### ISSUE TITLE
PneumaticCraft oil not generating

### ISSUE THREAD

**Issue by aaronhowser1** [TerraForged/tracker#146]
TeamPneumatic/pnc-repressurized/issues/488

**Comment by CreativeRealms** [comment]
For presets:
- Create preset
- Change settings
- Save preset
- Set as default
<img width="607" alt="Screenshot_4" src="https://user-images.githubusercontent.com/33978024/131196571-3fad0c11-4d9e-40c6-b229-03b2fa37f41c.png">
<img width="1875" alt="Screenshot_6" src="https://user-images.githubusercontent.com/33978024/131196588-9c67c1e4-dc37-48b1-bef1-130c1e0645ef.png">

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/131196629-5d63ed77-e7fe-46b6-ad69-defe45553a7e.png)
Done, thank you

**Comment by Won-Ton** [comment]
TF should ignore these oil lakes as of 0.2.15
