### ISSUE TITLE
Cave Biome API and dependencies not compatible with Terrafoged

### ISSUE THREAD

**Issue by GriSphera** [TerraForged/tracker#147]
Hi. I've been having this issue with Terraforged and Cave Biomes API, as the seconds content doesn't generate in a Terraforged world.
In this case, two mods that have this API as a requiered dependency, Caves and Cliffs Backport and Darker Depths, don't generate any of their features in a Terraforged generated world. The only thing that generates are the Caves and Cliffs Backported Mineshafts, and those generate just fine.
I'm not sure if it can be solved by Terraforged's side, if it is something that I'm configuring wrong, or if it even can solved at all, but I'd appreciate if you could take a look.
Forge version: Forge 1.16.5 - 36.2.0
Terraforged version: 0.2.14
Cave Biome API version: 1.16.5 - 1.3.7
Caves and Cliffs Backport version: 1.16.5 - 6.3
Darker Depths version: 1.16.5 - 1.1.1

**Comment by Won-Ton** [comment]
Not something we can fix sorry. Similar sorts of features will come when we update to 1.18 since they’ll be part of vanillas code base
