### ISSUE TITLE
possibly broken? byg:canyon_edge

### ISSUE THREAD

**Issue by cosmoderp** [TerraForged/tracker#148]
canyon edge biome from byg is just a giant flat area with one layer of water.  I am sharing a picture so you can see what I mean.  Does not feel intentional but I could be wrong.
https://cdn.discordapp.com/attachments/357332115869663232/884600631887814766/Untitled.png

**Comment by Won-Ton** [comment]
That’s a bug with byg. It’s an incomplete biome that they added by accident but still register it as if other mods should use it and I believe have refused to complete/remove/fix it
