### ISSUE TITLE
How to disable biomes from generation?

### ISSUE THREAD

**Issue by KostromDan** [TerraForged/tracker#150]
I want to prevet from generation all biomes from project vibrant journeys mod. I diabled all biomes in project vibrant journeys config. But it works only for default world type. Then i do whis in biome_weights.conf:
# Configure biome weights by entering their id and an integer value for their weight (default weight is 10)
# This config will override the weights configured or provided by other mods for TerraForged worlds only.
"terraforged:example_biome" = 10
overgrown_spires = -1
verdant_sands = -1
boreal_forest = -1
snowy_boreal_forest = -1
redwoods = -1
snowy_redwoods = -1
redwood_peaks = -1
pine_meadows = -1
alpine_heights = -1
boreal_plateau = -1
aspen_grove = -1
mangrove_marsh = -1
willow_wetlands = -1
baobab_fields = -1
prairie = -1
blossoming_fields = -1
autumnal_coniferous_forest = -1
crimson_thicket = -1
desert_shrubland = -1
red_rock_valley = -1
crystal_lakes = -1
windswept_cliffs = -1

also i tried "biome" = 0
But it no changes.
What i need to do?

**Comment by Won-Ton** [comment]
You need to use the full biome ID surrounded in quotes like the example shows.

The biome I’d consists of the modid and the biome name separated by a colon:
`”example_mod_id:example_biome”: 0`
