### ISSUE TITLE
Desert pyramids always underground.

### ISSUE THREAD

**Issue by DanAverin** [TerraForged/tracker#152]
How to prevent desert pyramids spawning underground?
I have /locate desert pyramids on random seed 10 times and havent found any pyramid not undeground.

**Comment by DanAverin** [comment]
Also i found what vanilla undeground dungeons always docked to caves. But with terraforged they not docked to caves.

**Comment by Won-Ton** [comment]
In vanilla pyramids are intended to generate at least partially underground. They are hardcoded to generate at a height close to sea level. I
