### ISSUE TITLE
rain sound missing in cold steppe

### ISSUE THREAD

**Issue by HentaiHamster** [TerraForged/tracker#153]
I saw another issue that was closed with the same problem where there is no sound for rain in the cold steppe(which im not even sure is this a vanilla biome??). I'm wondering what this is? Because like the other guy said the rain sounds come right back when you cross into another biome. Is there a way to add a missing sound file to the biome or something so the rain actually makes sounds?

**Comment by Won-Ton** [comment]
As mentioned in the other ticket that is the intended behaviour. +You can configure biomes using mojang's datapack system
