### ISSUE TITLE
Terraforge not generating Oh the Biome you'll go Nether and End Biomes

### ISSUE THREAD

**Issue by DefaultUSERNAME9** [TerraForged/tracker#160]
I was playing in my  survival Minecraft world and stumbled upon the nether and the end biomes from oh the biomes you'll go
does not generate is there a way to generate those biomes with out deleting my world

**Comment by Won-Ton** [comment]
You need to select byg’s generator for nether/end in TFs config screen before creating the world. There’s no way to modify it after the world has been created
