### ISSUE TITLE
Biomes of smaller mods don't get generated.

### ISSUE THREAD

**Issue by Ced7032** [TerraForged/tracker#163]
Biomes of the following mods did not generate in 1.16.5: "odd water mobs", "darker depths", "unnamed animals mod".
They do get loaded and when using the vanilla or BOP generator they do get generated aswell, but when using Terraforged, there does not seem to be any generation of these biomes. Using the command "locatebiome" also tells me that the biome wasn't found, so they're not just incredibly rare and actually don't generate.
I may be doing something wrong (Please tell me what if I do lol), but Biomes O' Plenty and Druidcraft generate just fine on Terraforged so idk.

**Comment by Won-Ton** [comment]
The mod that adds the biome needs to mark it for use in overworld - more info on our wiki
