### ISSUE TITLE
Crashed when loading new parts of map

### ISSUE THREAD

**Issue by ClockworkzAI** [TerraForged/tracker#164]
forge 36.2.4
Minecraft 1.16.5
Terraforge 0.2.15
Crashed 
This is in a mod pack with other mods. In crash_2021 you can see all mods.
It was running good until I load a area far from where I was before. causes to slow down until crashed
[crash-2021-11-15_21.02.36-server.txt](https://github.com/TerraForged/tracker/files/7541190/crash-2021-11-15_21.02.36-server.txt)
[latest.log](https://github.com/TerraForged/tracker/files/7541195/latest.log)

**Comment by Won-Ton** [comment]
Answered on discord. To recap: 
1. one of your other mods caused world-gen to deadlock and freeze
2. terraforged detected the freeze and tried to report it
3. a bug in forge/java (or combination of the two) meant the code that handles the reporting couldn't be loaded and so gave you different crash (the `NoClassDefFoundError` error message)

Can't help with either issue (ie  1 and 3) sorry.
I do notice you're not running in the official launcher and you have optifine installed. Either could be culprits idk
