### ISSUE TITLE
Beta2 Crash

### ISSUE THREAD

**Issue by Mr-Syntax** [TerraForged/tracker#165]
i am having this problem where on the default preset all the structures will generate
when i then try to make a new preset and up the seperation between monuments it completely disables those monuments on the new map then i go back into the creator and when i try to roll a new seed with those settings i get this cras
[crash-2021-11-17_23.37.19-client.txt](https://github.com/TerraForged/tracker/files/7558472/crash-2021-11-17_23.37.19-client.txt)
h

**Comment by Mr-Syntax** [comment]
if i delete all presets so it has to load the default all structures are there but if i change any settings certain structures will be missing like the towers of the wild

**Comment by Won-Ton** [comment]
Your client has somehow got into an invalid state. It looks like something has gone critically wrong before this crash and shut down part terraforged. Somehow the client stayed running and when you try to access the part of TF that is now shutdown you get this crash.

If you can reproduce with just TF installed feel free to report with steps taken.

Note however: I'm not here to debug every little problem with your modpack - you need to do your own due diligence and track which mod (or combination of mods) are the actual cause of your issues and then provide that investigative information to the relevant parties.
