### ISSUE TITLE
crashes on launching world

### ISSUE THREAD

**Issue by fasterthanfalcon** [TerraForged/tracker#167]
multiple crashes involving air_carvers, big pack so the issue could be anywhere, but when reading the crash log & swapping in and out mods that might be the issue, I've noticed they're fairly random, but only happen on world load, not world gen (chunk pregen), and every time it crashed it would show a different mod that was causing terraforged (and the entire game) to crash.

Upon launching into pre generated (grey) worlds without any of the mods it would work fine, and when launching into pre generated AND pre loaded (not grey) worlds WITH the mods labeled as "issues" it would work fine. 

My dumbass thought of this as a green light and I would pre-gen the world with the mods, close MC and remove them to launch the world, then close MC again and add back the "incompatable" mods, and everything would launch and work fine "then why not just keep doing that?" Would you want to re build your PC everytime you start it? same energy. But the issue is that this isn't working consistantly, "terraforged" keeps adding more mods to the "badboy" list (performant, then sulfuric, then waystones, then MCMT, and now BYG).

After multiple attempts I think this might be an issue with terraforged and not the other mods that are involved with the crash.
(i know many of my mods have incompatability and stability issues, that's why im providing multiple crash logs for this)
here are multiple examples of the crash on different worlds

--> https://pastebin.com/7aQk9UWs (sulfuric and performant) "no compat" well they've been working fine together for me
--> https://pastebin.com/GrJJUngA (just sulfuric)
--> https://pastebin.com/zWWNMdbk (what appears to be MCMT/BYG) "mcmt is unstable" true, so I pull it and then...
--> https://pastebin.com/u4kgjenu (just BYG) 

it might be an issue with running out of biome ID's, I'm not sure how 1.16 handles this since I'm used to 1.12 and we had ID mods.
or it might just be an issue with BYG...
"just remove BYG then" I'd rather not, and if it turns out to be an issue with BYG and I've made a fool of myself here, then I'll follow up with them. I'd appreciate any help since I'm sure I've missed something.

**Comment by Won-Ton** [comment]
You need to report to the creator of the modpack you're using. Looks like they're shipping an invalid config
