### ISSUE TITLE
Beta2 Menu Crash

### ISSUE THREAD

**Issue by Mr-Syntax** [TerraForged/tracker#168]
[crash-2021-11-25_23.45.38-client.txt](https://github.com/TerraForged/tracker/files/7605439/crash-2021-11-25_23.45.38-client.txt)

i know that you said your not here to debug my pack but i just thought id notify you of this crash since thats all what the log says

its still the same issue with some structures being missing when using custom presets

**Comment by Won-Ton** [comment]
That one’s an issue in forge
