### ISSUE TITLE
terraforge is not generating better end and  better nether reforged biomes

### ISSUE THREAD

**Issue by Kacperrrrrrr** [TerraForged/tracker#169]
As in title. I tried all the options in  terraforge config  files but it  is simply not working.All the mods are for forge. after changing terrain generation to deafult the problem dissapears.

here are the mods:
https://www.curseforge.com/minecraft/mc-mods/betternether-reforged
https://www.curseforge.com/minecraft/mc-mods/betterend-forge-port

**Comment by Won-Ton** [comment]
You need to set their generator(s) as the nether/end generator inside TF's configuration screen
