### ISSUE TITLE
Generation of modded structures

### ISSUE THREAD

**Issue by maxanier** [TerraForged/tracker#17]
It seems like modded structures (`net.minecraft.world.gen.feature.structure.Structure`) are not generating in the TerraForged world type. At least I can confirm that for the hunter tents in Vampirism (https://github.com/TeamLapen/Vampirism/issues/830).

As far as I know, we are correctly registering the structures: https://github.com/TeamLapen/Vampirism/blob/40a173005304e22929e2455a89364fb2dba64bf3/src/main/java/de/teamlapen/vampirism/core/ModFeatures.java#L55
Works with vanilla anyway.
Is this intentional or can we do something about that?

MC 1.16
Forge 35.1.17
TerraForged 1.16.4-0.2.0-RC 3
Vampirism 1.7.2

**Comment by Won-Ton** [comment]
Other mods' structures seem to be generating just fine.

I think you're just adding your `StructureSeparationSettings` too late - when I start the client and create a new TF world no vamp structures are generating, but backing out and creating a second TF world they do.

**Comment by maxanier** [comment]
Ah, yes, we are only adding them in `ServerAboutToStart`. 
The separation is configurable via the server config which is only available when loading/creating a world.
Guess we will have to move the config to common then or find a different solution.

Thank you for investigating
