### ISSUE TITLE
1.18.1 Terraforged Alpha 1 has no menu under worldgen setting

### ISSUE THREAD

**Issue by Tsoccerguy3** [TerraForged/tracker#172]
**PLEASE PROVIDE DETAILED INFORMATION, LOGS, CRASH-REPORTS.**  
[Search for existing issues before opening a new one.](https://github.com/TerraForged/tracker/issues?q=)  
_Note: we are not accepting feature requests/questions. Just bugs pls :]_

Using forge-1.18.1-39.0.7
I just got this mod off the Curseforge site
I can not see how to configure the worldgen settings and no instructions posted

**Comment by CreativeRealms** [comment]
There is no point making bug reports for a mod that is clearly not finished. Also, reading changelogs might be beneficial in the future. I have posted them below so you can do so now.

This is a very early build of TerraForged for 1.18.1.
Please consider it an early-stage development 'snapshot' (much like those that Mojang release). _**Please do not report bugs or compatibility issues using this version. We know it is not stable or well tested yet, but it will become so as development continues.**_

As such:
_**-It is is not suitable for modpack design/creation.
-It probably is not suitable for serious survival play.
-Future updates will probably not work with worlds created on this version.
-Many features and customization options are not yet implemented.
-Mod and datapack compatibility is not thoroughly tested.
-Some vanilla world-gen features have not yet been implemented.
-This version does not provide a world-type option (when you create a new world TerraForged should get used automatically).**_
