### ISSUE TITLE
Crash On World Gen

### ISSUE THREAD

**Issue by EightBlade** [TerraForged/tracker#178]
So I'm playing a custom modpack, and when I try to generate a world it crashes. It worked before, but I tweaked some settings in OptiFine and now it's spitting terraforged error logs at me.

https://pastebin.com/7hMBgbPP

Here's the log it gave.

**Comment by Won-Ton** [comment]
The crash is occurring during world-gen mob-spawning. Could be a misconfigured or faulty mod that adds mobs, you'd have to debug your modpack (or report it to the author of the modpack to debug).
