### ISSUE TITLE
BYG dummy biome appearing with Terraforged worlds 

### ISSUE THREAD

**Issue by aaronhowser1** [TerraForged/tracker#179]
FTBTeam/FTB-Modpack-Issues/issues/656

Apparently BYG has a dummy biome that isn't supposed to spawn, but is being used in Terraforged worlds.

**Comment by Won-Ton** [comment]
It's a bug in byg: at some point they published their mod with debug/unfinished biome(s) in it and I think they are reluctant to remove it/them through fear of potentially breaking existing world-saves (that's the only reason I can think of, at-least. Alternatively they could complete the unfinished biome and it'd generate normally).

A workaround: You can set the weight of problematic biomes to zero in TerraForged's biome-weights config file.
