### ISSUE TITLE
(compatibility) Biomes from "Oh the biomes you'll go" mod are not generated in nether and end dimensions.

### ISSUE THREAD

**Issue by Koji-KAWAHARA** [TerraForged/tracker#18]
The combination of "Oh the biomes you'll go (BYG)" mod and the terraforged works perfect in the overworked.
Although, additional biomes from BYG does not appear in the nether and end dimensions. All I can find is vanilla biomes.
MC 1.16.4
Forge 35.1.13
Terraforged 0.2.0-RC-3
Oh the biomes you'll go 1.1.6

**Comment by Won-Ton** [comment]
You need to specifically select BYG's nether/end generators in TF's options screen otherwise it uses default (vanilla)

**Comment by Koji-KAWAHARA** [comment]
Thanks for quick reply. I found a solution to this thanks to your comment and several other posts elsewhere.

The problem was that BYG do not have specific generator for nether and end. It provides list of custom biomes to vanilla terrain generator. This made it impossible to configure in TF's option setting.

The walk around for this is to modify level.dat, after generating the world with vanilla nether/end gen. One need to use NBTExplorer to do this.

Changes are : 
@ level.dat/Data/WorldgenSettings/dimensions/minecraft:the_end/generator/biome_source/
 rewrite "type:minecraft:the_end" to "type:byg:bygend" 

@ level.dat/Data/WorldgenSettings/dimensions/minecraft:nether/generator/biome_source/
 rewrite "type:minecraft:nether" to "type:byg:bygnether" 

Worked well for single player world.

**Comment by Rafii2198** [comment]
If there is Quark in a modpack then it is possible to work around this by setting quark:realistic for both Nether and End generator. It will then generate all the biomes from all mods for these dimensions.
