### ISSUE TITLE
buggy worldgen 

### ISSUE THREAD

**Issue by codec-d** [TerraForged/tracker#182]
see screen shot https://imgur.com/kn0kP6q

default settings, using biomes O' plenty, graveyard, and vampirism

**Comment by Won-Ton** [comment]
Hi is the world actually bugged in-game or does it just render oddly on maps?

Also; what minecraft and mod version?

If it's bugged in-game then I'm afraid you probably have a corrupted world - that could have been caused by any number of things but they're all external of TerraForged.

**Comment by codec-d** [comment]
Hello,

> Hi is the world actually bugged in-game or does it just render oddly on maps?

In game, theres a mish-mash of biomes in some regions when out exploring. The screen shot of the map was just to show the whole thing. it doesn't appear to be biome specific.

> Also; what minecraft and mod version?

1.16.5

> If it's bugged in-game then I'm afraid you probably have a corrupted world - that could have been caused by any number of things but they're all external of TerraForged.

this was my 3rd attempt at world gen

**Comment by codec-d** [comment]
this was closed prematurely
