### ISSUE TITLE
Crash: "The game crashed whilst generating mob spawns (terraforged world-gen)"

### ISSUE THREAD

**Issue by ghost** [TerraForged/tracker#186]
I have multiple mods installed that add mobs but have disabled most of their spawns (including default Minecraft mobs) either via their respective configs, or via the BadMobs mod.

Thus, the world I am traversing is essentially empty. However, while flying around, every 5 minutes or so I will get a crash, apparently due to Terraforged world-gen.

Here is a screenshot and the crash report:

<img width="599" alt="Screen Shot 2022-05-30 at 22 46 27" src="https://user-images.githubusercontent.com/17407989/171057817-66eed2f4-1dd9-4cae-ac50-61e9524ed9ac.png">

[crash-2022-05-30_22.44.31-client.txt](https://github.com/TerraForged/tracker/files/8800674/crash-2022-05-30_22.44.31-client.txt)

**Comment by Won-Ton** [comment]
Hi, this isn't caused by TerraForged, it'll be one of your mods that adds or modifies mob spawns. You'd need to figure out which mod is the problem and report to them.
