### ISSUE TITLE
Flat cut lakes

### ISSUE THREAD

**Issue by Hukenon** [TerraForged/tracker#188]
When using terraforged generation, sometimes lakes will generate completely flat, without any terrain smoothing like a hole in otherwise great generation. 

I assume it must be a mod compatibility issue, though I have no idea what mod would do this, and if it's possible to stop it. Here's all the mods I have running:
 
![Screenshot 2022-06-02 152824](https://user-images.githubusercontent.com/76778350/171732315-87e8a63c-25b1-4d14-b9c3-ee46d36f1d4b.png)

![2022-06-02_15 17 17](https://user-images.githubusercontent.com/76778350/171731232-6823ca5a-8b10-464c-9285-c87a4b990fe0.png)
![2022-06-02_15 16 56](https://user-images.githubusercontent.com/76778350/171731235-0908dfc4-e109-4b70-bf78-68409b2e6e5e.png)
![2022-06-02_15 17 04](https://user-images.githubusercontent.com/76778350/171731238-bed23327-67dc-430b-987a-6408f830c941.png)

**Comment by Won-Ton** [comment]
Use F3 to find out which mod's biome it is and then set its weight to zero in terraforged's `biome_weights.conf` file
