### ISSUE TITLE
Crash a few minutes after starting the game.

### ISSUE THREAD

**Issue by Wachecheiro** [TerraForged/tracker#193]
The problem seems to be exclusive to the "terraforged and distant horizons" mix, the crash does not happen if "default" or "biomes or plenty" is used in the world type selection.

The game crashes very similarly with "Ice and Fire: Dragons" and with "Valhelsia Structures", (always using terraforged).

This crash happens with almost all versions of terraforged (1.16.5), I didn't try all of them but most of them and the crash persists.

Here the crash:

---- Minecraft Crash Report ---- // You're mean.

Time: 16/07/22 06:28 PM Description: generating features & structures (TerraForged World-Gen)

com.terraforged.mod.profiler.watchdog.UncheckedException: Critical error detected whilst generating Feature [iceandfire:ice_dragon_cave] Caused by: java.lang.NullPointerException: No chunk exists at [406, 272] at net.minecraft.world.gen.WorldGenRegion.func_180495_p(WorldGenRegion.java:560) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:roadrunner.mixins.json:gen.chunk_region.ChunkRegionMixin,pl:mixin:A} at com.terraforged.mod.chunk.fix.RegionDelegate.func_180495_p(RegionDelegate.java:111) ~[terraforged:1.16.5-0.2.16-BETA-2] {re:classloading} at com.github.alexthe666.iceandfire.world.gen.WorldGenDragonCave.lambda$createShell$0(WorldGenDragonCave.java:102) ~[iceandfire:2.1.10-1.16.5] {re:classloading} at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_332] {} at com.github.alexthe666.iceandfire.world.gen.WorldGenDragonCave.createShell(WorldGenDragonCave.java:101) ~[iceandfire:2.1.10-1.16.5] {re:classloading} at com.github.alexthe666.iceandfire.world.gen.WorldGenDragonCave.generateCave(WorldGenDragonCave.java:92) ~[iceandfire:2.1.10-1.16.5] {re:classloading} at com.github.alexthe666.iceandfire.world.gen.WorldGenDragonCave.generate(WorldGenDragonCave.java:66) ~[iceandfire:2.1.10-1.16.5] {re:classloading} at com.github.alexthe666.iceandfire.world.gen.WorldGenDragonCave.func_241855_a(WorldGenDragonCave.java:34) ~[iceandfire:2.1.10-1.16.5] {re:classloading} at net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55) ~[?:?] {re:classloading,re:mixin} at com.terraforged.mod.chunk.generator.FeatureGenerator.redirect$zzg000$wrapDecorate$FeaturePlace(FeatureGenerator.java:541) ~[terraforged:1.16.5-0.2.16-BETA-2] {re:mixin,re:classloading,pl:mixin:APP:lod.mixins.json:MixinTFChunkGenerator,pl:mixin:A} at com.terraforged.mod.chunk.generator.FeatureGenerator.decorate(FeatureGenerator.java:166) ~[terraforged:1.16.5-0.2.16-BETA-2] {re:mixin,re:classloading,pl:mixin:APP:lod.mixins.json:MixinTFChunkGenerator,pl:mixin:A} at com.terraforged.mod.chunk.generator.FeatureGenerator.decorate(FeatureGenerator.java:106) ~[terraforged:1.16.5-0.2.16-BETA-2] {re:mixin,re:classloading,pl:mixin:APP:lod.mixins.json:MixinTFChunkGenerator,pl:mixin:A} at com.terraforged.mod.chunk.generator.FeatureGenerator.generateFeatures(FeatureGenerator.java:88) ~[terraforged:1.16.5-0.2.16-BETA-2] {re:mixin,re:classloading,pl:mixin:APP:lod.mixins.json:MixinTFChunkGenerator,pl:mixin:A} at com.terraforged.mod.chunk.TFChunkGenerator.func_230351_a_(TFChunkGenerator.java:250) ~[terraforged:1.16.5-0.2.16-BETA-2] {re:classloading} at forge.com.seibel.lod.common.wrappers.worldGeneration.step.StepFeatures.generateGroup(StepFeatures.java:70) ~[lod:1.6.5a] {re:classloading} at forge.com.seibel.lod.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateDirect(BatchGenerationEnvironment.java:581) ~[lod:1.6.5a] {re:classloading} at forge.com.seibel.lod.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateLodFromList(BatchGenerationEnvironment.java:452) ~[lod:1.6.5a] {re:classloading} at forge.com.seibel.lod.common.wrappers.worldGeneration.GenerationEvent.lambda$new$0(GenerationEvent.java:75) ~[lod:1.6.5a] {re:classloading} at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_332] {} at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_332] {} at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_332] {} at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_332] {} at java.lang.Thread.run(Thread.java:832) [?:1.8.0_332] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
-- Current Chunk -- Details: Pos: [404, 271] Status: features Structure Starts: [dungeoncrawl:dungeon, iceandfire:graveyard, iceandfire:mausoleum, minecraft:igloo, minecraft:mineshaft, minecraft:pillager_outpost, minecraft:ruined_portal, minecraft:stronghold, minecraft:village, mowziesmobs:frostmaw_spawn, mowziesmobs:wrought_chamber, valhelsia_structures:spawner_dungeon] Structure Refs: [dungeoncrawl:dungeon, minecraft:buried_treasure, minecraft:mineshaft, mowziesmobs:wrought_chamber, valhelsia_structures:spawner_dungeon]

-- TerraForged ChunkGenerator -- Details: Seed: 1757325628 Settings: {"miscellaneous":{"smoothLayerDecorator":true,"strataRegionSize":600,"strataDecorator":true,"oreCompatibleStoneOnly":true,"erosionDecorator":true,"plainStoneErosion":false,"naturalSnowDecorator":true,"customBiomeFeatures":true,"vanillaLakes":false,"vanillaSprings":true,"vanillaLavaLakes":true,"vanillaLavaSprings":true,"mountainBiomeUsage":0.4,"volcanoBiomeUsage":0.4},"dimensions":{"bedrockLayer":{"material":"minecraft:bedrock","minDepth":1,"variance":4},"dimensions":{"nether":"default","end":"default","includeExtraDimensions":true}},"structures":{"stronghold":{"distance":32,"spread":3,"count":128,"salt":0,"constrainToBiomes":false,"disabled":false},"structures":{"dungeoncrawl:dungeon":{"spacing":24,"separation":12,"salt":10387313,"disabled":false},"iceandfire:gorgon_temple":{"spacing":16,"separation":8,"salt":342226464,"disabled":false},"iceandfire:graveyard":{"spacing":48,"separation":24,"salt":342226432,"disabled":false},"iceandfire:mausoleum":{"spacing":30,"separation":15,"salt":342226464,"disabled":false},"minecraft:bastion_remnant":{"spacing":27,"separation":4,"salt":30084232,"disabled":false},"minecraft:buried_treasure":{"spacing":1,"separation":0,"salt":0,"disabled":false},"minecraft:desert_pyramid":{"spacing":32,"separation":8,"salt":14357617,"disabled":false},"minecraft:endcity":{"spacing":20,"separation":11,"salt":10387313,"disabled":false},"minecraft:fortress":{"spacing":27,"separation":4,"salt":30084232,"disabled":false},"minecraft:igloo":{"spacing":32,"separation":8,"salt":14357618,"disabled":false},"minecraft:jungle_pyramid":{"spacing":32,"separation":8,"salt":14357619,"disabled":false},"minecraft:mansion":{"spacing":80,"separation":20,"salt":10387319,"disabled":false},"minecraft:mineshaft":{"spacing":1,"separation":0,"salt":0,"disabled":false},"minecraft:monument":{"spacing":32,"separation":5,"salt":10387313,"disabled":false},"minecraft:nether_fossil":{"spacing":2,"separation":1,"salt":14357921,"disabled":false},"minecraft:ocean_ruin":{"spacing":20,"separation":8,"salt":14357621,"disabled":false},"minecraft:pillager_outpost":{"spacing":32,"separation":8,"salt":165745296,"disabled":false},"minecraft:ruined_portal":{"spacing":40,"separation":15,"salt":34222644,"disabled":false},"minecraft:shipwreck":{"spacing":24,"separation":4,"salt":165745296,"disabled":false},"minecraft:stronghold":{"spacing":1,"separation":0,"salt":0,"disabled":false},"minecraft:swamp_hut":{"spacing":32,"separation":8,"salt":14357620,"disabled":false},"minecraft:village":{"spacing":32,"separation":8,"salt":10387312,"disabled":false},"mowziesmobs:barakoa_village":{"spacing":25,"separation":8,"salt":123444792,"disabled":false},"mowziesmobs:frostmaw_spawn":{"spacing":25,"separation":8,"salt":1237654784,"disabled":false},"mowziesmobs:wrought_chamber":{"spacing":15,"separation":5,"salt":123555792,"disabled":false},"valhelsia_structures:big_tree":{"spacing":30,"separation":8,"salt":35122016,"disabled":false},"valhelsia_structures:castle":{"spacing":40,"separation":8,"salt":16987356,"disabled":false},"valhelsia_structures:castle_ruin":{"spacing":35,"separation":8,"salt":14357618,"disabled":false},"valhelsia_structures:desert_house":{"spacing":30,"separation":8,"salt":14862926,"disabled":false},"valhelsia_structures:forge":{"spacing":30,"separation":8,"salt":12857691,"disabled":false},"valhelsia_structures:player_house":{"spacing":30,"separation":8,"salt":17357644,"disabled":false},"valhelsia_structures:spawner_dungeon":{"spacing":30,"separation":8,"salt":23498568,"disabled":false},"valhelsia_structures:tower_ruin":{"spacing":25,"separation":8,"salt":24357670,"disabled":false},"valhelsia_structures:witch_hut":{"spacing":25,"separation":7,"salt":70882952,"disabled":false}}},"world":{"continent":{"continentType":"MULTI_IMPROVED","continentShape":"EUCLIDEAN","continentScale":3000,"continentJitter":0.7,"continentSkipping":0.25,"continentSizeVariance":0.25,"continentNoiseOctaves":5,"continentNoiseGain":0.26,"continentNoiseLacunarity":4.33},"controlPoints":{"deepOcean":0.1,"shallowOcean":0.25,"beach":0.327,"coast":0.448,"inland":0.502},"properties":{"spawnType":"CONTINENT_CENTER","worldHeight":256,"seaLevel":63}},"climate":{"temperature":{"seedOffset":0,"scale":6,"falloff":2,"min":0.0,"max":0.98,"bias":0.05},"moisture":{"seedOffset":0,"scale":6,"falloff":1,"min":0.0,"max":1.0,"bias":0.0},"biomeShape":{"biomeSize":225,"macroNoiseSize":8,"biomeWarpScale":150,"biomeWarpStrength":80},"biomeEdgeShape":{"type":"SIMPLEX","scale":24,"octaves":2,"gain":0.5,"lacunarity":2.65,"strength":14}},"terrain":{"general":{"terrainSeedOffset":0,"terrainRegionSize":1200,"globalVerticalScale":0.98,"globalHorizontalScale":1.0,"fancyMountains":true},"steppe":{"weight":1.0,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"plains":{"weight":2.0,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"hills":{"weight":2.0,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"dales":{"weight":1.5,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"plateau":{"weight":1.5,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"badlands":{"weight":1.0,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"torridonian":{"weight":2.0,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"mountains":{"weight":2.5,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"volcano":{"weight":5.0,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0}},"rivers":{"seedOffset":0,"riverCount":8,"mainRivers":{"bedDepth":5,"minBankHeight":2,"maxBankHeight":6,"bedWidth":8,"bankWidth":20,"fade":0.75},"branchRivers":{"bedDepth":4,"minBankHeight":1,"maxBankHeight":4,"bedWidth":5,"bankWidth":14,"fade":0.975},"lakes":{"chance":0.3,"minStartDistance":0.0,"maxStartDistance":0.03,"depth":10,"sizeMin":75,"sizeMax":150,"minBankHeight":2,"maxBankHeight":10},"wetlands":{"chance":0.6,"sizeMin":175,"sizeMax":225}},"filters":{"erosion":{"dropletsPerChunk":135,"dropletLifetime":12,"dropletVolume":0.7,"dropletVelocity":0.7,"erosionRate":0.5,"depositeRate":0.5},"smoothing":{"iterations":1,"smoothingRadius":1.8,"smoothingRate":0.9}}}

-- TerraForged BiomeProvider -- Details: Overworld Biomes: [biomesoplenty:alps, minecraft:badlands, minecraft:badlands_plateau, biomesoplenty:bamboo_blossom_grove, minecraft:bamboo_jungle, biomesoplenty:bayou, biomesoplenty:bayou_mangrove, minecraft:beach, minecraft:birch_forest, terraforged:bryce, biomesoplenty:burnt_forest, biomesoplenty:cherry_blossom_grove, biomesoplenty:cold_desert, terraforged:cold_marshland, minecraft:cold_ocean, terraforged:cold_steppe, biomesoplenty:coniferous_forest, biomesoplenty:coniferous_lakes, minecraft:dark_forest, biomesoplenty:dead_forest, biomesoplenty:deep_bayou, minecraft:deep_cold_ocean, minecraft:deep_frozen_ocean, minecraft:deep_lukewarm_ocean, minecraft:deep_ocean, minecraft:deep_warm_ocean, biomesoplenty:dense_marsh, biomesoplenty:dense_woodland, minecraft:desert, minecraft:desert_lakes, biomesoplenty:dry_boneyard, biomesoplenty:dryland, minecraft:eroded_badlands, biomesoplenty:fir_clearing, terraforged:fir_forest, minecraft:flower_forest, biomesoplenty:flower_meadow, terraforged:flower_plains, minecraft:forest, terraforged:frozen_lake, terraforged:frozen_marsh, minecraft:frozen_ocean, minecraft:frozen_river, biomesoplenty:fungal_field, biomesoplenty:fungal_jungle, minecraft:giant_spruce_taiga, minecraft:giant_tree_taiga, biomesoplenty:golden_prairie, biomesoplenty:grassland, biomesoplenty:grassland_clover_patch, biomesoplenty:gravel_beach, minecraft:gravelly_mountains, biomesoplenty:grove, biomesoplenty:grove_clearing, biomesoplenty:grove_lakes, biomesoplenty:highland, biomesoplenty:highland_crag, biomesoplenty:highland_moor, minecraft:ice_spikes, biomesoplenty:jade_cliffs, minecraft:jungle, minecraft:jungle_edge, terraforged:lake, biomesoplenty:lavender_field, biomesoplenty:lavender_forest, minecraft:lukewarm_ocean, biomesoplenty:lush_desert, biomesoplenty:lush_savanna, biomesoplenty:marsh, terraforged:marshland, biomesoplenty:meadow, biomesoplenty:meadow_forest, minecraft:modified_badlands_plateau, minecraft:modified_gravelly_mountains, minecraft:modified_jungle, minecraft:modified_jungle_edge, minecraft:modified_wooded_badlands_plateau, minecraft:mountains, minecraft:mushroom_field_shore, minecraft:mushroom_fields, biomesoplenty:muskeg, biomesoplenty:mystic_grove, biomesoplenty:mystic_plains, minecraft:ocean, biomesoplenty:ominous_mire, biomesoplenty:ominous_woods, biomesoplenty:orchard, projectvibrantjourneys:overgrown_spires, minecraft:plains, biomesoplenty:prairie, biomesoplenty:rainforest, biomesoplenty:rainforest_cliffs, biomesoplenty:rainforest_floodplain, biomesoplenty:redwood_forest, biomesoplenty:redwood_forest_edge, minecraft:river, minecraft:savanna, minecraft:savanna_plateau, terraforged:savanna_scrub, biomesoplenty:scrubland, biomesoplenty:seasonal_forest, biomesoplenty:seasonal_orchard, biomesoplenty:seasonal_pumpkin_patch, minecraft:shattered_savanna, minecraft:shattered_savanna_plateau, terraforged:shattered_savanna_scrub, biomesoplenty:shroomy_wetland, biomesoplenty:shrubland, minecraft:snowy_beach, biomesoplenty:snowy_coniferous_forest, biomesoplenty:snowy_fir_clearing, terraforged:snowy_fir_forest, biomesoplenty:snowy_maple_forest, minecraft:snowy_mountains, minecraft:snowy_taiga, minecraft:snowy_taiga_mountains, minecraft:snowy_tundra, terraforged:steppe, terraforged:stone_forest, minecraft:stone_shore, minecraft:sunflower_plains, minecraft:swamp, minecraft:taiga, minecraft:taiga_mountains, terraforged:taiga_scrub, minecraft:tall_birch_forest, biomesoplenty:tall_dead_forest, biomesoplenty:tropic_beach, biomesoplenty:tundra, biomesoplenty:tundra_basin, biomesoplenty:tundra_bog, projectvibrantjourneys:verdant_sands, biomesoplenty:volcanic_plains, biomesoplenty:volcano, terraforged:warm_beach, minecraft:warm_ocean, biomesoplenty:wasteland, biomesoplenty:wetland, biomesoplenty:wetland_forest, minecraft:wooded_badlands_plateau, minecraft:wooded_mountains, biomesoplenty:wooded_scrubland, biomesoplenty:woodland]

-- TerraForged Biome Weights Config -- Details: terraforged:example_biome: 10

-- TerraForged Profiler -- Details: Timings: Section Count Time MS Min MS Max MS Average MS structure_starts 4563 3839 0 1273 0,84 structure_refs 2691 9435 0 1038 3,51 biomes 2691 2580 0 341 0,96 terrain 2691 17301 2 426 6,43 surface 2690 4156 0 118 1,54 air_carvers 1001 1330 0 113 1,33 fluid_carvers 1001 415 0 368 0,41 decoration 2463 26967 1 580 10,95 mob_spawns 691 165 0 24 0,24 structure_searches 0 0 0 0 0,00 Sum 26,21

-- System Details -- Details: Minecraft Version: 1.16.5 Minecraft Version ID: 1.16.5 Operating System: Windows 10 (amd64) version 10.0 Java Version: 1.8.0_332, IBM Corporation Java VM Version: Eclipse OpenJ9 VM (JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20220422_375 (JIT enabled, AOT enabled) OpenJ9 - 9a84ec34e OMR - ab24b6666 JCL - 0b8b8af39a based on jdk8u332-b09), Eclipse OpenJ9 Memory: 803994384 bytes (766 MB) / 2310799360 bytes (2203 MB) up to 4294967296 bytes (4096 MB) CPUs: 4 JVM Flags: 13 total; -Xoptionsfile=C:\Program Files\Semeru\jdk-8.0.332.9-openj9\jre\bin\default\options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse29 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec ModLauncher launch target: fmlclient ModLauncher naming: srg ModLauncher services: /mixin-0.8.4.jar mixin PLUGINSERVICE /eventbus-4.0.0.jar eventbus PLUGINSERVICE /forge-1.16.5-36.2.35.jar object_holder_definalize PLUGINSERVICE /forge-1.16.5-36.2.35.jar runtime_enum_extender PLUGINSERVICE /accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE /forge-1.16.5-36.2.35.jar capability_inject_definalize PLUGINSERVICE /forge-1.16.5-36.2.35.jar runtimedistcleaner PLUGINSERVICE /mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE /forge-1.16.5-36.2.35.jar fml TRANSFORMATIONSERVICE FML: 36.2 Forge: net.minecraftforge:36.2.35 FML Language Providers: javafml@36.2 minecraft@1 Mod List: forge-1.16.5-36.2.35-client.jar |Minecraft |minecraft |1.16.5 |DONE |Manifest: NOSIGNATURE DistantHorizons-1.6.5a-1.16.5.jar |Distant Horizons |lod |1.6.5a |DONE |Manifest: NOSIGNATURE dynamiclightsreforged-mc1.16.5_v1.0.1.jar |Dynamic Lights Reforged |dynamiclightsreforged |mc1.16.5_v1.0.1 |DONE |Manifest: NOSIGNATURE mowziesmobs-1.5.25.jar |Mowzie's Mobs |mowziesmobs |1.5.25 |DONE |Manifest: NOSIGNATURE DungeonCrawl-1.16.5-2.3.9.jar |Dungeon Crawl |dungeoncrawl |2.3.9 |DONE |Manifest: NOSIGNATURE randompatches-2.4.4-forge.jar |RandomPatches |randompatches |2.4.4-forge |DONE |Manifest: 92:f6:29:d4:09:89:f5:f5:98:5e:20:34:31:d0:7b:58:22:06:bd:a5:d1:6a:92:6e:ac:3d:8d:18:c5:b2:5b:d7 BiomesOPlenty-1.16.5-13.1.0.487-universal.jar |Biomes O' Plenty |biomesoplenty |1.16.5-13.1.0.487 |DONE |Manifest: NOSIGNATURE projectvibrantjourneys-1.16.5-3.0.1.jar |Project: Vibrant Journeys |projectvibrantjourneys |1.16.5-3.0.1 |DONE |Manifest: NOSIGNATURE magnesium-1.5.jar |Magnesium |magnesium |1.5 |DONE |Manifest: NOSIGNATURE starlight-forge-1.0.0-RC2-1.16.5.jar |Starlight |starlight |1.0.0-RC2 |DONE |Manifest: NOSIGNATURE helium-1.0.jar |Helium |helium |1.0 |DONE |Manifest: NOSIGNATURE magnesium_extras-mc1.16.5_v1.3.1.jar |Magnesium Extras |magnesium_extras |mc1.16.5_v1.3.1 |DONE |Manifest: NOSIGNATURE forge-1.16.5-36.2.35-universal.jar |Forge |forge |36.2.35 |DONE |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90 valhelsia_core-16.0.15.jar |Valhelsia Core |valhelsia_core |16.0.15 |DONE |Manifest: NOSIGNATURE valhelsia_structures-1.16.5-0.1.6.jar |Valhelsia Structures |valhelsia_structures |1.16.5-0.1.6 |DONE |Manifest: NOSIGNATURE subwild-1.3.1.jar |Subterranean Wilderness |subwild |1.3.1 |DONE |Manifest: NOSIGNATURE geckolib-forge-1.16.5-3.0.81.jar |GeckoLib |geckolib3 |3.0.81 |DONE |Manifest: NOSIGNATURE TerraForged-1.16.5-0.2.16-BETA-2.jar |TerraForged |terraforged |0.2.16-BETA-2 |DONE |Manifest: 7b:73:d0:a2:c3:40:13:84:35:4f:c9:0e:2b:85:8c:08:ea:3c:3c:eb:f1:98:8b:5b:6e:ca:8a:a0:9a:cf:12:b3 Fallingleaves-1.16.3-1.2.4.jar |Falling Leaves |fallingleaves |1.2.4-alpha+20220121|DONE |Manifest: NOSIGNATURE FastSuite-1.16.4-1.1.1.jar |FastSuite |fastsuite |1.1.1 |DONE |Manifest: NOSIGNATURE RoadRunner-mc1.16.5-1.4.1.jar |Meep Meep! (Road Runner) |roadrunner |1.4.1 |DONE |Manifest: NOSIGNATURE Placebo-1.16.5-4.7.0.jar |Placebo |placebo |4.7.0 |DONE |Manifest: NOSIGNATURE citadel-1.8.1-1.16.5.jar |Citadel |citadel |1.8.1 |DONE |Manifest: NOSIGNATURE alexsmobs-1.12.1.jar |Alex's Mobs |alexsmobs |1.12.1 |DONE |Manifest: NOSIGNATURE iceandfire-2.1.10-1.16.5.jar |Ice and Fire |iceandfire |2.1.10-1.16.5 |DONE |Manifest: NOSIGNATURE Crash Report UUID: 4b527cef-88a6-4434-8307-38080c31111c RoadRunner != Lithium: This instance was launched using RoadRunner, which is an unofficial Lithium fork! Please do not report bugs to them!

**Comment by Won-Ton** [comment]
This isn't TerraForged's fault sorry, but an issue with distant horizons &/or those structure mods you mentioned
