### ISSUE TITLE
Biomes You'll Go guiana biomes not generating correctly

### ISSUE THREAD

**Issue by ghost** [TerraForged/tracker#194]
byg:guiana_clearing, byg:guiana_shield, and byg:guiana_springs end up looking like regular jungle biomes with Terraforged on

**Comment by Won-Ton** [comment]
The only thing about biomes that TF "changes" is the terrain that they get placed on.

Some vanilla & mod biomes exist purely to provide different terrain in the vanilla world generation, but since TF does terrain very differently those biomes don't behave the same way.
