### ISSUE TITLE
Game crashes when generating rogue spawner structure from the apotheosis mod

### ISSUE THREAD

**Issue by Ariostraza** [TerraForged/tracker#195]
> The game crashed whilst generating features & structures (terraforged world-gen)
Error: com.terraforged.mod.profiler.watchdog.UncheckedException: Critical error detected whilst generating Feature [apotheosis:rogue_spawner]

It seems that terraforged is having issues generating the rogue spawner from apotheosis.
That said im not code-savy so i cant say much about what any of this means.
In my mod list as you can see i do have the Distant Horizons mod which pre-generates the world in less detail to provide a farther render distance.
Whether or not its terraforged or apotheosis's fault is beyond me.
Besides that i chose the "_Terraforged - Beautiful_" setting, not sure if that has anything to do with it.

here's the crash report:
[crash-2022-07-30_22.05.10-client.txt](https://github.com/TerraForged/tracker/files/9227860/crash-2022-07-30_22.05.10-client.txt)
Here's some a little too compressed footage of how it goes

https://user-images.githubusercontent.com/110314910/182006126-be6310d1-d59e-4329-8f1b-c286cef7daf2.mp4

**Comment by Won-Ton** [comment]
Hi It's not terraforged, TF is just reporting the crash.

I'd guess it was the lod mod but you'll have to trial-and-error it
