### ISSUE TITLE
Common_setup error

### ISSUE THREAD

**Issue by SaquaX** [TerraForged/tracker#199]
An error has occurred. TerraForged (terraforged) throws an error in common_setup event stage I can't fix it anyway
Any help would be appreciated

TerraFrorged(terraforged) encountered an error druing the common_setup event phase

com.electronwill.nightconfig.core.io.parsingexception: not enough data available

Minecraft Version 1.16.5
Terraforged Version 0.2.15

i use translate
sorry

**Comment by Won-Ton** [comment]
Hi, it sounds like you have an invalid config somewhere.
Try delete TerraForged's config folder (`.minecraft/config/terraforged`).

Please post the full logs if that doesn't help.
