### ISSUE TITLE
Ignoring other mods generation/spawning configs.

### ISSUE THREAD

**Issue by Tombstone101** [TerraForged/tracker#20]
Using TerraForged-1.16.4-0.2.0-RC-3, I'm getting disabled structures and mobs from other mods (ex. ice and fire and quark).
These configs load properly when not using "terraforged" world type on a dedicated server.

**Comment by Won-Ton** [comment]
Not sure what you mean?

TF doesn't disable other mods' stuff. It doesn't read their configs for them either. Both are handled by the mod adding the structure.

**Comment by Tombstone101** [comment]
I dont know how else to say it. My server including its configs run and include or disable exactly what i enable/disable in mod configs. Having the only change being restarting with the terraforged world type. Everything that is disabled is ignored and included in generation. So wether the intent is not to touch the other configs, something is clearly happening to ignore them on creation of a new world. Thanks

**Comment by Won-Ton** [comment]
It sounds like those mods need to read and react to their own config files when other world-types are selected. 

The way this works is: 
1. Mods choose what content they want to add to each biome, how much of it, how it's configured etc
2. TF uses those biomes to decorate the world

We have a 'biome_weights.conf' file to configure how frequently a given biome appears, but content inside the biome is entirely decided by vanilla/mods.

**Comment by Tombstone101** [comment]
Thanks. I will defer this to those whom configs are misbehaving.
