### ISSUE TITLE
The crash may be due to terraforged

### ISSUE THREAD

**Issue by Sergo467** [TerraForged/tracker#201]
[crash-2022-10-11_14.34.49-client.txt](https://github.com/TerraForged/tracker/files/9768601/crash-2022-10-11_14.34.49-client.txt)

**Comment by Won-Ton** [comment]
Huh that's a new one. Yes the crash is coming from TerraForged.

My guess is that this is using custom world-gen settings with some settings cranked a bit further than is probably sensible, but nevertheless should be accounted for within the area of code that is crashing.
