### ISSUE TITLE
1.16 The world stopped running

### ISSUE THREAD

**Issue by Accidey** [TerraForged/tracker#202]
Specific performance for the entire world of the creatures stopped not moving, the world stopped loading, can not return to the main interface, can only force to end the game. I'm not quite sure if it's a TerraForged problem, but please help me. This is the crash log.
[crash-2022-12-17_19.54.32-client.txt](https://github.com/TerraForged/tracker/files/10251708/crash-2022-12-17_19.54.32-client.txt)
[2022-12-17-6.log.gz](https://github.com/TerraForged/tracker/files/10251711/2022-12-17-6.log.gz)

**Comment by Won-Ton** [comment]
Hi, from the logs it looks like it could be an incompatiblity between any one of the following mods: MoStructures, Waystones, OuterEnd, Optifine.

You'll have to debug your modpack to determine which mods are conflicting (or report the crash to the modapck maker if that isn't you). It doesn't look to be related to TerraForged
