### ISSUE TITLE
Slightest customization of Terraforged results in world creation freezing, or locked out of older worlds.

### ISSUE THREAD

**Issue by ThatLittleCrab** [TerraForged/tracker#204]
Terraforged only works if I do not customize it, when I only want to scale the continents down.

I have a txt file containing all of the log info here, though it might not help because it had been stuck at 10% generation for at least 15 minutes.
[Uploading log file.txt…]()

**Comment by Won-Ton** [comment]
Hi you'll need to try upload that log again please as it seems not to have worked

**Comment by ThatLittleCrab** [comment]
I did, but even now, it's not finished loading. I will have to paste it into a linked document instead.

**Comment by ThatLittleCrab** [comment]
How do I open/unclose this? (first time on github rlly)

I cant upload the log, it took 3 hours and it didnt upload. Nothing uploads so im making a google doc link instead. :|

Lastest.log in doc form
https://docs.google.com/document/d/1DRoVihI21vFXpPCk7FpAgirWVOWOEQ-z9OJB3MgukCo/edit
