### ISSUE TITLE
New version breaks terrain

### ISSUE THREAD

**Issue by SaeneA** [TerraForged/tracker#22]
Hey,

Minecraft 1.16.4
Forge 35.1.36

I have the issue of updating to the newest version of terraforged braking the world. And I don't really know how to fix it, I've read that if I try it with the old version it will work, but shouldn't I regenerate that area? And for the world generation to stay as terraforged I can't update the mod?

Thanks, SaeneA

P.S. This is my survival world, and I really don't want to lose it :))

**Comment by Won-Ton** [comment]
Hi, the 1.16 version of the mod is not compatible with 1.15 (due to the massive changes Mojang made). Stay on 1.15 if you don't want to start a new world
