### ISSUE TITLE
Can Terraforge Suddenly "Stop"?

### ISSUE THREAD

**Issue by thedeerirty** [TerraForged/tracker#23]
**PLEASE PROVIDE DETAILED INFORMATION, LOGS, CRASH-REPORTS.**  
[Search for existing issues before opening a new one.](https://github.com/TerraForged/tracker/issues?q=)  
_Note: we are not accepting feature requests/questions. Just bugs pls :]_

Version: 1.16.5

Hey! Sorry if I'm reporting this in an incorrect format, but I've noticed what could be a bug? I'm not actually sure if this is unlucky generation or not, but it suddenly seems like my world just... stopped generating Terraforge terrain, or something? I could just be misremembering how vanilla looks, but it doesn't appear to look like Terraforge-styled generation. It started out like that, when I was exploring my world, before I sorta hit like an "edge". By edge, I mean the biome I was in just stopped like it hit an invisible barrier or something, and then started generating differently. I'll include a screenshot of this generation real quick and I can walk back and find this "edge" I'm mentioning. At least I hope I remember the direction. 
![2021-01-23_16 56 31](https://user-images.githubusercontent.com/58305182/105615161-7db18780-5d9c-11eb-8d19-baa24a41c0a4.png)

**Comment by thedeerirty** [comment]
![2021-01-23_17 06 55](https://user-images.githubusercontent.com/58305182/105615655-6a082000-5da0-11eb-95c5-b4a168d1b5da.png)
![2021-01-23_17 25 51](https://user-images.githubusercontent.com/58305182/105615674-70969780-5da0-11eb-97b1-f798fb21c7d9.png)

Went ahead and tried to find it, as you can see it seems like the river I screenshotted is generated in vanilla style.

**Comment by Won-Ton** [comment]
If you opened the world without TF installed at any point then yes it will switch to using vanilla for new chunks (even if you reinstall TF later).

**Comment by thedeerirty** [comment]
I don't believe I did
I think Antique Atlas might have done something? I remember it crashing upon trying to load the world after installing it, after I had already made the world

**Comment by thedeerirty** [comment]
[crash-2021-01-23_14.02.26-server.txt](https://github.com/TerraForged/tracker/files/5862540/crash-2021-01-23_14.02.26-server.txt)
here's the report in case that'd help, but I could be reading this wrong; I just know atlas did something, and then when I explore beyond where I had before, it was that vanilla generation.

**Comment by Won-Ton** [comment]
nothing to do with TF sorry
