### ISSUE TITLE
Crash with TF and Youngs Better Caves

### ISSUE THREAD

**Issue by Cr4fTJuNkiE** [TerraForged/tracker#28]
Crash Report:

[crash-2021-01-27_19.02.29-client.txt](https://github.com/TerraForged/tracker/files/5883870/crash-2021-01-27_19.02.29-client.txt)

**Comment by Cr4fTJuNkiE** [comment]
Hopefully there is a fix soon. Love both of these mods!

**Comment by Brittank88** [comment]
Btw, this was already addressed in #7.

**Comment by Won-Ton** [comment]
Yeah was an issue in YBC. Update it or wait for them to release the update which fixes it
