### ISSUE TITLE
FML defaultWorldType = "terraforged:terraforged" Not Working

### ISSUE THREAD

**Issue by Brittank88** [TerraForged/tracker#29]
`Minecraft 1.16.5`
`Forge 36.0.1`
`TerraForged 0.2.0`

_P.S. this same issue also occurs in Forge version `35.1.37` for `MC 1.16.4`._

Here's my [Latest.log](https://pastebin.com/BDErF5wF), even though I'm not sure there's anything in the log.

Despite setting `defaultWorldType = "terraforged:terraforged"` in `forge-common.toml`, nothing changes whatsoever.

Please do let me know if I actually need to be lodging a bug report with the FML devs!

**Comment by Won-Ton** [comment]
A simple test would be to do that with just forge+terraforged. You should find that it works correctly.
Some other mod is probably force injecting itself as the world-type.

**Comment by Brittank88** [comment]
Ah, I understand. Do you know if there would be any concise way for me to determine which mod may be doing this? Anything I can search for in the log? Any commands I could run?

I feel that adding back over 230 mods bit by bit is not going to work very well.

**Comment by Won-Ton** [comment]
When you create a new world check what the world-type is set to before creating the world.

If it's set to 'default' then forge's feature is probably broken.

If it's any other mods' than the one you have set in your forge config then that mod has overridden it.

If it's set to the terraforged world-type but when you create the world it's clearly not a terraforged world, then a mod is either doing something nasty to hijack it or it could contain a datapack that replaces the world-gen. In both these cases, it's very difficult to track down - you'd have to use "the remove half of the mods, test, repeat" until you narrow down the offender

**Comment by Brittank88** [comment]
Alright, thank you for the advice!

**Comment by Brittank88** [comment]
For any future users who have this issue, it was in fact Biomes O' Plenty. I don't know why it took this long to click with me, but you can fix it with a change to `configs/biomesoplenty/client.toml`:
![image](https://user-images.githubusercontent.com/24266948/107092357-8eabcf80-6857-11eb-99db-7de6fd1fc28f.png)
