### ISSUE TITLE
Terraforged conflicts with Betterend

### ISSUE THREAD

**Issue by JustReg2Download** [TerraForged/tracker#3]
When you go to the end, betterend's biomes do not generate at all when you picked "terraforged" world option.
![2021-01-14_11 57 23](https://user-images.githubusercontent.com/72761693/104575482-ca3fe900-565f-11eb-9145-17b3ace6bd85.png)
![2021-01-14_11 57 28](https://user-images.githubusercontent.com/72761693/104575489-cb711600-565f-11eb-92f9-4b0d601866f5.png)
In a screenshot you may see that Betterend mod is actually active due to custom skybox and new mob, everything looks good until you try to find any custom biome with "/locatebiome" command.

**Comment by Won-Ton** [comment]
This is an issue with betterend. I believe they're working on a fix - when it's updated with the fix you'll be able to select betterend as the end generator in terraforged's world options screen (second page at the bottom)
