### ISSUE TITLE
Crash with latest Terraforged version (0.2.3)

### ISSUE THREAD

**Issue by gglobensky** [TerraForged/tracker#30]
When I create a world with the latest version of Terraforged and Better caves, the game crashes back to the launcher. If I use the 0.2.0 Beta-8 version of the Terraforged mod which was on at the time Better caves released, I can make a world without a problem.

Thanks for the excellent mod btw.

**Comment by Won-Ton** [comment]
Logs and crash report pls

**Comment by gglobensky** [comment]
log -> https://drive.google.com/file/d/1gFoDDikp2YTREpCjCLw8UtQc5hJVwEV1/view?usp=sharing
crash report -> https://drive.google.com/file/d/1LV-tFgUz03iMM6LUpeC8x3Jd97U-f_Yv/view?usp=sharing

I narrowed it down to a crash when I select better end forge as the biome generator for the end.
When I use something else, it seems fine.

I retract myself, changing Terraforged version does not seem to change anything.

**Comment by Won-Ton** [comment]
can't access those. drag-drop into the issue comment box to upload to github or use a paste site

**Comment by bkellkell** [comment]
Having the same issue here. Only Terraforged, better end, and abnormals core installed.

Only crashes when generating a Terraforged world type with a set seed (whether set manually or set by the terraforged customization screen)

Versions:
+MC 1.16.4 or 1.16.5
+forge 35.1.37 or 36.0.14
+Terraforged-1.16.4-0.2.3
+betterendforge-1.16.4-1.4.1
+abnormals_core-1.16.4-3.0.6

log: 
[crash-2021-02-04_21.52.42-client.txt](https://github.com/TerraForged/tracker/files/5929818/crash-2021-02-04_21.52.42-client.txt)

**Comment by bkellkell** [comment]
The crash does not happen if better end's world type is selected as the end generator in the Terraforged customization settings.

**Comment by Won-Ton** [comment]
Hi thanks for the logs. This isn't caused by TF
