### ISSUE TITLE
Bee nests do not generate

### ISSUE THREAD

**Issue by FreeFull** [TerraForged/tracker#31]
Tested using a 1.16.5 pack with just Terraforged 0.2.3, JEI and Forge, with the default Terraforged preset and settings. Things attempted:
* Repeatedly growing an oak sapling next to a flower, with command blocks to remove logs and leaves to speed up the process
* Flying around minecraft:plains and minecraft:flower_forest biomes.

I have not been able to get a single bee nest to generate from sapling growth or natural generation, which renders vanilla bees unobtainable.

**Comment by Won-Ton** [comment]
They do generate. Will double check the sapling behaviour though

**Comment by FreeFull** [comment]
Would the real bug be that the probability is way too low, then? I have grown way over 100 oak saplings without a single bee nest appearing. In vanilla Minecraft, the probability of getting a bee nest is 5%, and the chance of having at least one bee nest after growing 100 saplings next to a flower is 99.4%
