### ISSUE TITLE
Spawn underground

### ISSUE THREAD

**Issue by AttilaPapp** [TerraForged/tracker#32]
Hi, I am using the latest (TerraForged-1.16.4-0.2.3.jar) version. I change the ocean level from 64 to 84 and I keep spawning underground. It might be considered as not a bug, but I believe the intended behavior on day one would be to spawn on terrain, under the sun, not in a cave. Thank you

**Comment by Won-Ton** [comment]
Works fine here. Note that if you push your world settings to extremes then the spawn search can fail to find a valid position within a reasonable distance. In that case it'll set the world spawn at `x:0 z:0 y:water-level+1` and then minecraft will place as close to that as it can (be that in a cave or at the surface)
