### ISSUE TITLE
Terraforged incompatible with mountain type biomes from vanilla and other mods.

### ISSUE THREAD

**Issue by theboo** [TerraForged/tracker#33]
So after a bunch of testing, i have found that terraforged does not work with mountain biome types from any mod/vanilla because it does not set any biome area to terrain:mountain biome-type:cold/medium/warm... This means that any biomes from the list below will not generate(including the vanilla biomes). 

The "fix" for this seems to be to crank up the "mountain biome usage" slider, but terraforged mountain generation(while super awesome dispersed throughout other biomes) can severely ruin the aesthetic of many of these mountain biomes when it generates the entire biome as a terraforged mountain range rather than generating it as just the biome with TF mountains dispersed throughout.

I have tried messing with temperature settings, but the only biome types that form in the cold areas are taiga and tundra. I believe there is plenty of room to disperse some  cold/medium/warm biome types in the generation. Or maybe a setting to turn on these biome types in world gen.

I've tried to keep this away from being a BYG compatibility issue, but BYG seems to be one of the most used mods with terraforged, so a bit of compat work for this might be a good thing. Almost all of byg biomes look absolutely stunning with terraforged generation.

list below:
```  
"mountain": {
    "COLD": [
      "byg:bluff_peaks",
      "byg:bluff_steeps",
      "byg:dover_mountains",
      "byg:skyris_highlands",
      "minecraft:gravelly_mountains",
      "minecraft:modified_gravelly_mountains",
      "minecraft:mountains",
      "minecraft:snowy_mountains",
      "minecraft:snowy_taiga_mountains",
      "minecraft:taiga_mountains",
      "minecraft:wooded_mountains"
    ],
    "MEDIUM": [
      "byg:cika_mountains"
    ],
    "WARM": [
      "byg:red_rock_mountains",
      "byg:redwood_mountains",
      "byg:wooded_red_rock_mountains"

**Comment by theboo** [comment]
another idea would be to give us the ability to override the biome type with a biome_map.conf similar to what we are able to do with the biome_weights.conf

**Comment by Won-Ton** [comment]
TF is designed to not need mountain biomes because mountaina are a type of terrain that can sustain many different biomes.

The usage slider was provided for the people that care more about visiting every biome (or whatever), but it unfortunately comes at the cost of aesthetics because it's working against the principles that TF is built around (separating the idea of biomes from terrain).
