### ISSUE TITLE
Add astral sorcery shrine structures to terrain helper

### ISSUE THREAD

**Issue by theboo** [TerraForged/tracker#34]
I totally get if this is outside the scope of terraforged, but it would be really cool to get some terrain helper compat for structures like the astral sorcery shrines. Currently they will generate like this if a mountain if formed underneath them:

![image](https://user-images.githubusercontent.com/3585761/107102674-11894780-67d0-11eb-9b8c-2ad0c7ba2bf4.png)
![image](https://user-images.githubusercontent.com/3585761/107105761-c6296600-67dc-11eb-91b6-9e3e19748eea.png)

i was hoping they could possibly be added to the terrain helper at: https://github.com/TerraForged/TerraForged/blob/55aed0079de7237835291afb673f22a8e2652248/src/main/java/com/terraforged/mod/chunk/TerrainHelper.java

they are regular nbt structures and show up in the TF structures menu.

astral structures: https://github.com/HellFirePvP/AstralSorcery/tree/1.16-indev/src/main/resources/data/astralsorcery/structures

**Comment by Won-Ton** [comment]
Hey do they a base generated for them in default world-gen?

**Comment by Merlo17** [comment]
Not 100% sure if this is what you're asking but yes, they are supposed to have a basement like that in vanilla astral worldgen. That's where loot and progression stuff actually is, and normally it would be underground

**Comment by Won-Ton** [comment]
I understand they're not meant to be half floating in the air. I'm meaning does the vanilla generator build up the terrain around the structure when it generates on slopes etc?

**Comment by theboo** [comment]
no, the vanilla generator does not build up around them on slopes. It just floats.

**Comment by theboo** [comment]
well... i have never seen one on a slope tbh lol... regular minecraft world gen is so flat haha

**Comment by theboo** [comment]
actually, it looks like they do get terrain built around them in default worldgen:
![image](https://user-images.githubusercontent.com/3585761/107121755-feff2480-6848-11eb-93aa-b6829faaa240.png)

**Comment by Merlo17** [comment]
They do. Quoting people in Astral's discord

> Not directly, but still yes
> It ties into the vanilla generation system, so any terrain around it is vanilla's doing.

**Comment by Ridanisaurus** [comment]
As a workaround, I attempted to modify the NBT for the structure to give them depth, and make the floary-ness less terrible looking, but sadly that broke the `minecraft:void_structure` so that's a no-go.
Terraforged Support for this would be the most optimal and ideal solution to help them blend in the terrain.

**Comment by Won-Ton** [comment]
Yeah I'll have a look at it. We currently just do it for village pieces because that's all we did in 1.15.2.
It'll probably need to be size limited but shouldn't be an issue with the structures shown in the example screenshots

**Comment by Ridanisaurus** [comment]
Your consideration is much appreciated as more and more mods are adding their own modded structures, and it would amazing to have this compatibility between Terraforged and other mods to make sure the world remains as beautiful as possible.

**Comment by Won-Ton** [comment]
Added to 0.2.5. It's not from flawless, and I wasn't able to find any extreme examples like in the screenshots to test but should be better than nothing.

**Comment by Ridanisaurus** [comment]
After some testing, I can confirm that this fix is working like a charm. Much appreciated.
![image](https://user-images.githubusercontent.com/64355028/107156510-07597b80-697f-11eb-82a3-c0c273767658.png)
![image](https://user-images.githubusercontent.com/64355028/107156514-0c1e2f80-697f-11eb-8729-3e5a885a5ea7.png)
![image](https://user-images.githubusercontent.com/64355028/107156519-104a4d00-697f-11eb-8e37-854fe3d67b9f.png)
