### ISSUE TITLE
Porting world from 1.15.2 to 1.16.5

### ISSUE THREAD

**Issue by DevyHeavy** [TerraForged/tracker#35]
Hi,

I am moving my world and modpack from 1.15.2 (that had TerrForge installed) to 1.16.5 (which also has TerraForge installed).

After launching the server for the first time in 1.16.5 I noticed all the new terrain was vanillia. Looking at the server.properties files shows that instead of "level-type=terraforged" it is now "level-type=terraforged:/terraforged".

I am not able to not get TerraForge to not add the extra ":/terraforge" bit.

I understand that the versions are in someway not compatible (as in new terrain will not be seamless).

Is there any way to fix this?

**Comment by Won-Ton** [comment]
Hey. We were not able to support updating worlds from 1.15 to 1.16 due to vast changes to Minecraft's worldgen codebase (and knock-on effects to Forge). If you try to load a 1.15 TF world on 1.16 the generator gets reset to vanilla default so new chunks generate as vanilla.

**Comment by DevyHeavy** [comment]
Thanks for the answer.

I wonder what would happen if I generate a new world in 1.16.5 and then import the loaded chunks from 1.15.2 using MCEdit.
