### ISSUE TITLE
importing settings doesn't work in 1.16.5

### ISSUE THREAD

**Issue by Conversage** [TerraForged/tracker#36]
Hi,

i just started using this mod a few days ago and right now i am trying out all the different settings.
I just watched your video about them (https://www.youtube.com/watch?v=eW7OU8hZ--o) and tried implementing that .json with the settings you used in that video but it seems they dont work if used in 1.16.5. They literally dont change anything at all when imported.

I copied them in /minecraft/instances/Valhelsia3/config/terraforge/ .

Is there any solution to this? I really want to test those out, since i find it very hard to make a good world out of the current settings (they changed aswell compared to the video).

Best regards

Nils

**Comment by Won-Ton** [comment]
The person who made that video is not associated with TF and is using an old version of the mod on 1.15.2 that had different settings.
