### ISSUE TITLE
Strange version problem with MC 1.16.4

### ISSUE THREAD

**Issue by Normal69** [TerraForged/tracker#37]
Mod works in 1.16.5 - I've just recognized there is no recommended forge version for that.

Tried for an MC 1.16.4 version - the mod asks for a.16.5 forge, pack doesn't start.

Noticed a strange sentence in the changelog on curseforge.

"Version 0.2.0:

    - Runs on all versions of 1.16.5
    - Runs on 1.16.4 with forge version 35.1.5 or higher"

Forge 35.1.5 would be for 1.16.5, and not 1.16.4 - and it isn't even on forge offical download page.
There are only these:
...
36.0.10 	01/28/21 09:12 PM 	
36.0.9 	01/28/21 01:33 AM 	
36.0.8 	01/28/21 12:06 AM 	
36.0.7 	01/27/21 12:38 AM 	
36.0.4 	01/26/21 02:58 AM 	
36.0.2 	01/26/21 02:31 AM 	
36.0.1 	01/17/21 09:11 PM 	
36.0.0 	01/15/21 07:48 PM 	

Strange, eh? :)

**Comment by Won-Ton** [comment]
> "Show All Versions"

<img width="568" alt="Screenshot 2021-02-06 at 18 45 47" src="https://user-images.githubusercontent.com/71294196/107127109-d3f9ec80-68ab-11eb-82aa-dedfc358465b.png">
