### ISSUE TITLE
eyes of ender not working

### ISSUE THREAD

**Issue by shirls326** [TerraForged/tracker#39]
I have multiple world gen mods such as repurposed structures, BOP and BYE. I thought it was those mods so I eliminated BOP to see if it was that but it's like the eye of ender doesn't even leave my inventory. When I also drop it, it disappears. Although when I seem to do this on a normal world, the stronghold/modded stronghold seems to be there. I increased the chances through terraforge but the same glitch is happening. Help? ):

Edit 1: I runned a test where BOP/BYE/Quark were eliminated, but Repurposed structures are still in and the glitch is still happening

**Comment by Won-Ton** [comment]
Repurposed structures replaces the ender eye behaviour. The settings for their structures aren't registered properly for terraforged to use them so they either don't generate or can't be located.

I gave them a ~5 line fix for it already but they didn't seem receptive to using it. You could alternatively do the datapack thing I suggested in #38 . It's a bit labourious unfortunately
