### ISSUE TITLE
Datapack for Betterend which adds better end city is broken

### ISSUE THREAD

**Issue by JustReg2Download** [TerraForged/tracker#4]
I downloaded and did everything what it need (forge version of better end and datapack).
P.S. I even tried to load with terraforged and result is same.
![2021-01-14_12 50 19](https://user-images.githubusercontent.com/72761693/104581509-599cca80-5667-11eb-887b-fcccfbfaf2a9.png)
![2021-01-14_12 50 15](https://user-images.githubusercontent.com/72761693/104581536-63263280-5667-11eb-8fc2-3688688c903d.png)
![Uploading 2021-01-14_12.50.18.png…]()

**Comment by Won-Ton** [comment]
TF's only involvement with end generation is to offer you the choice of vanilla end-generation or a third-party mod's end-generation (if they have registered it with forge correctly).

Once that generator has been created it has nothing to do with TF.
