### ISSUE TITLE
Powerfailure leading to defaulting to BoP generation

### ISSUE THREAD

**Issue by Zygus42** [TerraForged/tracker#40]
TerraForged-1.16.4-0.2.4
forge-1.16.5-36.0.7-installer

Started a dedicated server with this as my customized settings:

[Dirks Version.json.txt](https://github.com/TerraForged/tracker/files/5943069/Dirks.Version.json.txt)

Started the world fine, and then had a power failure, restarted the server and then played again the next day.  Chunk edges all around where the chunks hadn't generated on day 1, and from that point on outwards, all standard BoP generation, not TerraForged.

These are from the server:

[server.properties.txt](https://github.com/TerraForged/tracker/files/5943087/server.properties.txt)
[latest.log.txt](https://github.com/TerraForged/tracker/files/5943089/latest.log.txt)
[debug.log.txt](https://github.com/TerraForged/tracker/files/5943091/debug.log.txt)

**Comment by Won-Ton** [comment]
TF plays no part in recovering the world after something like that. I don't know why bop specifically would override the world-type rather than it being reset to default gen.

Sounds like you'll need to restore the world from a backup or start a new one.
