### ISSUE TITLE
Issue with BYG

### ISSUE THREAD

**Issue by shirls326** [TerraForged/tracker#41]
When I try to go to the nether while terraforge is running, the game entirely crashes if I have BYG nether activated through the terraforge setting of creating a world.

https://pastebin.com/brCLAj24 This is the crash report I got when I tried to go to the nether.

I saw another issue with this but is there any other way other than accessing the level.dat file?

Thanks!

**Comment by Won-Ton** [comment]
Hi again. Looks like a bug in byg - somewhere in their maths they're dividing by zero. There could be external factors (config mistakes, incompatibilities with other mods, etc) that are causing that to happen but I wouldn't know what those might be. You'd need to report to them to get it fixed.

We don't support modifying the level.dat file, but if you do do that, keep organised backups of it and the world folder

**Comment by shirls326** [comment]
Thank you so much for a quick response :) I'll recheck my config and see what is going on with that
