### ISSUE TITLE
DeepOcean Level

### ISSUE THREAD

**Issue by TheCherry** [TerraForged/tracker#42]
Hi,

I do not like the depth of the deep ocean. The dungones are much too easy to reach because the ocean is not really deep. But when I adjust the Sea Level, it affects the normal generation on land as well. Thus, for example, mines can also spawn on the surface.  Am I doing something wrong? Or is it simply not possible to set the ocean deeper at the moment?

This happen with a lower Sea Level:
![Screenshot_20210210_093900](https://user-images.githubusercontent.com/1090782/107485284-dac28100-6b83-11eb-91d3-bbea42c4182c.png)

**Comment by Won-Ton** [comment]
A lot of vanilla & mod structures are hardcoded to appear a certain y-levels so changing the sea level can cause some weird things as you described. Increasing the sealevel would have been what I'd have suggested were it not for that. There's not really a good solution for it atm as it needs vanilla to unhardcode-ify all this stuff and then for mods to follow suit.

Other than that, we have sliders that let you control where shallow oceans appear and where deep oceans start in relation to each continent (the "Control Point" sliders). You could try movin the shallow ocean slider towards the beach slider, and then pull the deep_ocean slider up towards the shallow ocean one. That would have the effect of making the transition from beach to deep ocean much sharper and closer to the shoreline.
