### ISSUE TITLE
BoP and BYG biomes not appearing in the Nether

### ISSUE THREAD

**Issue by MarioSMB** [TerraForged/tracker#44]
I have a Forge server launched with default TerraForged settings, the overworld shows biomes from these two mods, but the Nether has only vanilla biomes. Both the mods' configs are set to have their biomes appear in the Nether by default, so I believe it is TerraForged not including them.

**Comment by Won-Ton** [comment]
There's an option in the TF config ui to select the nether/end generators. Select whichever mod your want to handle those dimensions there.

**Comment by MarioSMB** [comment]
I'm sorry, you may have misunderstood: I am running a server, not a singleplayer world. There is no preset, only a level-type option.  
The overworld is correctly populated by modded biomes, but the Nether is not.

This seems like a major flaw and incompatibility in the design of the mod, requiring the world to be created locally before it can be used on a server with Nether biomes, and very unintuitive for users (especially those who find this out *after* progressing far in the world), as it is not clearly documented that this is needed.

Additionally, BoP and BYG both have their options enabled to automatically populate the Nether with their biomes, it should *not* need a preset, just as the overworld does not need one.

Please reconsider this issue, so that other server admins don't fall into the same trap and become stuck with vanilla Nether biomes.

**Comment by Won-Ton** [comment]
This guide explains how to use presets on servers. You need to create the preset on your client as descirbed though:
https://github.com/TerraForged/community/wiki/Forge-Server
