### ISSUE TITLE
TerraForged overwriting Biome IDs

### ISSUE THREAD

**Issue by itsTort** [TerraForged/tracker#45]
**PLEASE PROVIDE DETAILED INFORMATION, LOGS, CRASH-REPORTS.**  
[Search for existing issues before opening a new one.](https://github.com/TerraForged/tracker/issues?q=)  
_Note: we are not accepting feature requests/questions. Just bugs pls :]_

Adding TerraForged to the server seems to have messed with the BiomeIDs and scrambled them to holy heck.   The Redwood Forest is now labeled a Lavedner field, the plains area is now a terraforged:snowy biome.  

The biomes themselves seem fine, just the names/ids are all out of whack.

----

----

Updating this with better information

Better detail of my lame report now that I got a moment. 

I was pregenerating a world last night. Everything was okee dokee. This morning I moved in our updated mods (but accidentally moved in Terraforged) and resumed Pregenerating. 

Terraforged was not setup through Server Properties or anything, so I believe it's just adding biomes to the world, and not doing anything to terrain generation. No profiles or presets were setup, the mod just ended up in the folder on accident. 

After the mod wound up in there, the Biome ID's appear super scrambled.  I.E the Redwood Forest is now a Lavender Forest, our starting spot was part of the Redwood Forest, however now it's transitioned into one of the Savannah Snowy Scrub biomes.

None of the terrain appears to be messed with, but all my Biome names are all wonky now. Some are accurate, like the Plains we had just outside the starter.   But many are odd. 

Considering the world wasn't really generated with TerraForged, and it only exists as a mod in the folder with no settings associated with it, if I remove Terraforged from the server/clients, will this cause issues if we ever discover the terrain that Terraforged Biomes would have been ,and will it potentially fix our scrambled Biome ID mess? 

Note that we've pregenned several hundred thousand chunks, so we're either stuck with it, or we aren't, was just hoping the fix wouldn't be so bad!

**Comment by itsTort** [comment]
closing issue until I can test whether optifine caused this or not.

**Comment by itsTort** [comment]
Better detail of my lame report now that I got a moment. 

I was pregenerating a world last night. Everything was okee dokee. This morning I moved in our updated mods (but accidentally moved in Terraforged) and resumed Pregenerating. 

Terraforged was not setup through Server Properties or anything, so I believe it's just adding biomes to the world, and not doing anything to terrain generation. No profiles or presets were setup, the mod just ended up in the folder on accident. 

After the mod wound up in there, the Biome ID's appear super scrambled.  I.E the Redwood Forest is now a Lavender Forest, our starting spot was part of the Redwood Forest, however now it's transitioned into one of the Savannah Snowy Scrub biomes.

None of the terrain appears to be messed with, but all my Biome names are all wonky now. Some are accurate, like the Plains we had just outside the starter.   But many are odd. 

Considering the world wasn't really generated with TerraForged, and it only exists as a mod in the folder with no settings associated with it, if I remove Terraforged from the server/clients, will this cause issues if we ever discover the terrain that Terraforged Biomes would have been ,and will it potentially fix our scrambled Biome ID mess? 

Note that we've pregenned several hundred thousand chunks, so we're either stuck with it, or we aren't, was just hoping the fix wouldn't be so bad!

**Comment by Won-Ton** [comment]
TF doesn't have anything to do with how biome ids are assigned or stored per world, that's a forge issue. We register our biomes with forge, forge adds them to the vanilla overworld chunkgenerator, they get assigned an id because that's how they're stored on disk.

Sounds like forge is not robust/smart enough to handle new biomes after a world has been created already so you should avoid adding new biome-providing mods after pregen'ing your world (doesn't help knowing that _now_ in your case unfortunately).

I thought forge had already addressed this in more recent versions but I guess not if you're up to date.
