### ISSUE TITLE
terraforged biome names 

### ISSUE THREAD

**Issue by oiirn29** [TerraForged/tracker#46]
hi, I'm trying to make a small modpack for me and my friends using the terraforged mod and I can't find a list of biomes that it adds, is there a way to find the names for the biomes?

**Comment by Won-Ton** [comment]
If you type `/locatebiome terraforged:` it'll list on TF biomes as suggestions.
Alternatively you can look [here](https://github.com/TerraForged/TerraForged/blob/0.2.x/src/main/java/com/terraforged/mod/biome/ModBiomes.java) and it's all the text shown like `createKey("cold_steppe");` <- that'd be `terraforged:cold_steppe`
