### ISSUE TITLE
Generation Crash.

### ISSUE THREAD

**Issue by deadspidervenom** [TerraForged/tracker#47]
While walking around the game suddenly crashes, it seems like a possible conflict with "When Dungeons Arise" but i am not sure as minecraft points too terraforged.

https://pastebin.com/hd6BhURv

EDIT: i made a bug report with the mod makers of "When Dungeons Arise" if you want to talk with them.
https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise/issues/5

**Comment by Won-Ton** [comment]
It's not pointing to TF, TF is just the one that has detected the error and has reported the crash.
You were right to report to WDA, they would need to address the cause by the looks of it
