### ISSUE TITLE
Terraforge makes my game crash? :<

### ISSUE THREAD

**Issue by mysticetus09** [TerraForged/tracker#48]
I noticed when I put this mod on the list and then start altering the map I wanted to create. I don't know if this inflicting one my mods. So I'm here to report since this mod is sus in one of the mods I'm using. 

[crash-2021-02-13_15.34.14-client.txt](https://github.com/TerraForged/tracker/files/5975296/crash-2021-02-13_15.34.14-client.txt)

**Comment by mysticetus09** [comment]
I found the mod which causing interference with Terraforged. It's the Better End mod. I don't mind removing the Better End since I'm comfortable with this Terraforged. But it might cause future issues when other people use both mods.

**Comment by Won-Ton** [comment]
I believe they have had this reported to them already and will be addressed in a future update (if it hasn't already been released)
