### ISSUE TITLE
Common_setup

### ISSUE THREAD

**Issue by Verysoapypotato** [TerraForged/tracker#49]
I'm trying to load it up with over twenty other mods I've deleted everyone and it still didn't work. My friends can load it up just fine. I've tried every fix I can find online but it won't do anything. **Also**, I have tried over three different versions of forge. The error I'm getting is something along the lines of "Common_setup error" Thank you.

**Comment by Won-Ton** [comment]
You need forge version 35.1.5 or newer + TerraForged 0.2.0 or newer (we recommend latest which is currently 0.2.7)

Feel free to post some logs/crash-report/actual details if you're still having issues but it's unlikely to be TF that's your issue here
