### ISSUE TITLE
Server Startup Failure When Missing Server.Properties

### ISSUE THREAD

**Issue by Spiker985** [TerraForged/tracker#5]
Minecraft: 1.16.4
Forge: 1.16.4-35.1.10
Terraforged: 1.16.4-0.2.0-beta6

When creating a server up from scratch, no prior installation or runs (aka no server.properties) while Terraforged is installed results in the server encountering a NullPointerException. Terraforged is attempting to access DimensionGeneratorSettings when there are none.

Disabling Terraforged, running an initial instance of the server long enough to generate the server.properties, and then enabling the mod works as expected.

I believe that Terraforged is attempting to access the settings incorrectly, resulting in a failure to start if the server.properties does not exist prior.

[Log of attempted start up](https://github.com/TerraForged/tracker/files/5818612/2021-01-14-4.log)

**Comment by Won-Ton** [comment]
Thanks will take a look
