### ISSUE TITLE
Crash on world creation

### ISSUE THREAD

**Issue by Moobien** [TerraForged/tracker#50]
**PLEASE PROVIDE DETAILED INFORMATION, LOGS, CRASH-REPORTS.**  
[Search for existing issues before opening a new one.](https://github.com/TerraForged/tracker/issues?q=)  
_Note: we are not accepting feature requests/questions. Just bugs pls :]_

getting the following crash on version 0.2.7, reverting to 0.2.6 alllows world creation.

https://gist.github.com/Moobien/26808d630ceda5b0021fa974e0df0827

**Comment by Won-Ton** [comment]
Hi. That's a bug with betterendforge. Has nothing to do with version 0.2.6 or .7 of TF

**Comment by Moobien** [comment]
ahh cool. cheers! btw totally love the scenery you guys generate!
