### ISSUE TITLE
TerraForged is not generating Create Stones

### ISSUE THREAD

**Issue by douglas725** [TerraForged/tracker#53]
**PLEASE PROVIDE DETAILED INFORMATION, LOGS, CRASH-REPORTS.**  
[Search for existing issues before opening a new one.](https://github.com/TerraForged/tracker/issues?q=)  
_Note: we are not accepting feature requests/questions. Just bugs pls :]_

Terraforged: 1.16.4-0.2.7.jar
Forge: 1.16.4 - 35.1.37
Create: create-mc1.16.3_v0.3e
Quark: Quark-r2.4-304

I decided to use Terraforged for compatibility with Emendatus Enigmatica strata ores, with Quark and Create stones, but Create stones are not being generated through Terraforged.

Is this a configuration error or is it a bug?

wg_stone.json
{
  "replace": true,
  "values": [
    "minecraft:stone",
    "minecraft:granite",
    "minecraft:diorite",
    "minecraft:andesite",
    "create:limestone",
    "create:weathered_limestone",
    "create:gabbro",
    "create:natural_scoria",
    "quark:marble",
    "quark:jasper",
    "quark:slate"
  ]
}

[create-common.txt](https://github.com/TerraForged/tracker/files/5983371/create-common.txt)
[quark-common.txt](https://github.com/TerraForged/tracker/files/5983372/quark-common.txt)
![2021-02-14_19 28 10](https://user-images.githubusercontent.com/19313015/107981351-a9411f80-6fa0-11eb-8ff2-fcd125cddca3.png)
[config-terraforged.zip](https://github.com/TerraForged/tracker/files/5983381/config-terraforged.zip)

**Comment by Won-Ton** [comment]
By default TerraForged will only use blocks from the `forge:wg_stone` tag if they allow ores to spawn in them (ie are also in the `minecraft:base_stone_overworld` tag).

There's an option in the misc settings to not do that check but it might make ores hard to find. You could instead copy-paste your wg_stone tag to make a base_stone_overworld one with the exact same set of blocks and it should then work.

**Comment by douglas725** [comment]
> By default TerraForged will only use blocks from the `forge:wg_stone` tag if they allow ores to spawn in them (ie are also in the `minecraft:base_stone_overworld` tag).
> 
> There's an option in the misc settings to not do that check but it might make ores hard to find. You could instead copy-paste your wg_stone tag to make a base_stone_overworld one with the exact same set of blocks and it should then work.

Okay, I'll try to do that. thanks.

**Comment by douglas725** [comment]
It worked, and thanks again

![2021-02-15_21 31 46](https://user-images.githubusercontent.com/19313015/108008407-12478800-6fdf-11eb-9d7f-c3ca920ca839.png)
