### ISSUE TITLE
[1.16.5] Some errors

### ISSUE THREAD

**Issue by FrannDzs** [TerraForged/tracker#54]
Hello! I am getting these kinds of errors, is this due to the latest changes in forge 36.0.42?

> [18feb2021 13:55:20.672] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.673] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.684] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.685] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.686] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.686] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.687] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.700] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.701] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.701] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.704] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.704] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.719] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.720] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.720] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.720] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.721] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.736] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.736] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.737] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.737] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.738] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.764] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.764] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.765] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.765] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.766] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.779] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.780] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.780] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.781] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.782] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.804] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.805] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.805] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.806] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.807] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.820] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.821] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.822] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.822] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.824] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.833] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.834] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.834] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.835] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.836] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.862] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.864] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.864] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]
> [18feb2021 13:55:20.865] [Server thread/ERROR] [FeatureManager/Codecs]: Value 128 outside of range [0:64]

It is possible that these errors come from TerraForged ?. I don't know who to refer the problem to, sorry if I'm wrong, greetings!

**Comment by Won-Ton** [comment]
TerraForged is reporting the errors but the errors themselves are caused by some other mod having configured one or more of its world-gen features incorrectly

**Comment by FrannDzs** [comment]
> TerraForged is reporting the errors but the errors themselves are caused by some other mod having configured one or more of its world-gen features incorrectly

Then I will see what mod is causing the problem, thanks!
