### ISSUE TITLE
Grass block below a snow block from generation

### ISSUE THREAD

**Issue by didis54** [TerraForged/tracker#56]
**PLEASE PROVIDE DETAILED INFORMATION, LOGS, CRASH-REPORTS.**  
[Search for existing issues before opening a new one.](https://github.com/TerraForged/tracker/issues?q=)  
_Note: we are not accepting feature requests/questions. Just bugs pls :]_
Hi,

In latest version 0.2.6+ of TerraForged
You added this:
- Set grass blocks to dirt when 2 or more layers of snow are placed on them as they'll eventually turn to dirt anyway though random block ticking

But with snow block added by the generation it's not doing it by default as you can see on the below screenshot
![image](https://user-images.githubusercontent.com/3106344/108510494-e2d69b00-72be-11eb-9a5b-2f9170461815.png)

**Comment by Won-Ton** [comment]
Caves & ravines breaking through the surface may interrupt the behaviour in certain situations. You can see to the right in the very same image that all the blocks are set to dirt.

**Comment by didis54** [comment]
There is no cave or ravin ?
It's near a river

But ok, i mean a snow block is theoretically counting as more than 2 layers of snow thats why i tought it was looking strange when i saw it

Thanks for the answer
