### ISSUE TITLE
TerraForged World-Gen Replaced with Default after server update to 1.16.5

### ISSUE THREAD

**Issue by Akrione** [TerraForged/tracker#57]
Hi, sorry for posting this question in the pull-requests section earlier. That was my mistake.

I've been running a server for a few months and generated it in 1.15.2 with TerraForged. I've recently ported the save file into a 1.16.5 server where I've kept the configs the same. However, when I reached the edge of world generation made in 1.15.2, the default Minecraft world-gen kicks on and cuts TerraForged off. I've made backups and created copies of both to splice the chunks players altered in 1.16.5 into the previous 1.15.2 world file with MCA Selector in hopes of catching the save before the issue began. Unfortunately, this came back with the same world-gen issue as before.

Are there any known issues with TerraForged and version advancement to 1.16 from an older MC world?

If so, is there any known fix, or will I have to say in the pre-generated areas from now on?

**Comment by Won-Ton** [comment]
1.15.2 TF worlds aren't compatible with 1.16+
