### ISSUE TITLE
TerraForged and Biomes Yo Go

### ISSUE THREAD

**Issue by SaytoROG** [TerraForged/tracker#58]
TerraForged dont Spawn Moded Biome's from Biomes Yo Go 

even if all Biomes have the Tag "Overworld"

Forge 1.16.5

**Comment by Won-Ton** [comment]
Works just fine. Check your logs & that you've installed the right files.

![2021-02-19_18 27 22](https://user-images.githubusercontent.com/71294196/108545772-1fff5500-72e0-11eb-9672-12b43e5c37c5.png)
