### ISSUE TITLE
Empty Biomes

### ISSUE THREAD

**Issue by SaytoROG** [TerraForged/tracker#59]
The Biomes Yo GO biomes
are generated

But they are generated empty.
The trees do not appear in most biomes

**Comment by SaytoROG** [comment]
![2021-02-19_19 47 53](https://user-images.githubusercontent.com/38839152/108547922-6a3a0380-72eb-11eb-8db8-4bd6554f30c0.png)

**Comment by Won-Ton** [comment]
We don't make BYG
