### ISSUE TITLE
Terraforged stops generating after adding biomes mod

### ISSUE THREAD

**Issue by Matthysse** [TerraForged/tracker#61]
Hello! I added the environmental mod to my modpack, in which there already was Biomes'o'plenty and other abnormals mods, but in my existing world, when I load new chunks, they aren't Terraforged world type anymore:
![2021-02-21_21 28 48](https://user-images.githubusercontent.com/32510957/108639750-6c8c9100-7496-11eb-9801-6acfc2b076d9.png)
I don't understand why it just stops generating the world as a terraforged world type. 
In addition, it creates chunk borders, that would be awesome if Terraforged could completely remove this well-known minecraft bug (trying to scan what biomes there are continue loading the new chunks with it, by connecting the blocks?)

**Comment by Won-Ton** [comment]
The issue isn't caused by TF and is not something TF can fix. I couldn't tell you what the issue _is_ based on the minimal detail that you provided tbh
