### ISSUE TITLE
Server Process hangs when stopping server with Forge + TerraForged

### ISSUE THREAD

**Issue by xToken** [TerraForged/tracker#62]
Reproduced with Forge 36.0.10 and 36.0.42 and TerraForged 0.2.7 only

With brand new installation of forge and default TerraForged settings (only update is to set level-type=terraforged)
One note is that after launching the server the server.properties file is updated with level-type=terraforged\:terraforged

Launching the server via the .jar file directly works correctly, /stop will fully stop and shutdown the server
If the server is launched via command line or terminal /stop does not work, the server process appears to shutdown but never terminates (thus making restarting servers regularly quite difficult)

**Comment by Won-Ton** [comment]
Thanks. I have been able to reproduce and I think I have a solution. Will be available in the next mod version

**Comment by IdrisQe** [comment]
Good to know it'll be fixed soon! I just spent a solid hour stopping and restarting my server with various mods removed to figure out what was causing this! Until then, just to confirm, there's no risk to the world or install from closing the terminal when it hangs like that, correct?

**Comment by Won-Ton** [comment]
No there'd be no risk as long as you've let the server run through full shutdown procedure before terminating it. The 'saving chunks' and 'chunks saving complete' (paraphrasing) messages come fairly early on in that process
