### ISSUE TITLE
Vanilla structure generation issue

### ISSUE THREAD

**Issue by sirben99** [TerraForged/tracker#63]
Hey!

Im going to try to explain this as well as i can, so please bear with me on this one.

I noticed for a long time that when using Terrafoge, the vanilla structures are very weird to locate.

What i mean by this? When using /locate command, or better yet Greater eye of ender mod (https://www.curseforge.com/minecraft/mc-mods/greater-eye-of-ender-forge) the distance of the structures seem to be very weird. For example: Use /locate in one spot, it says 300 blocks away. Move little to the left, and its 2k blocks away. 

I have a gif demonstrating this in action here: https://gyazo.com/9d92c59287e28268b0f7c8cc2671ad4e
And here: https://gyazo.com/69d34c5e9115bd579b0d62b325baf344

As you can see, the pearls go to different direction, and even the /locate command confuses it self.
I can confirm that this never or very really happens in vanilla overworld setting.

This bug has been in Terraforged for a while now, and i really would like to see this solved. 
I hope you got the gist of what i was trying to say, since its a very weird issue to explain.

If you need anything from me (Like logs etc) please say so. 
I attachted the latest log to this issue
[latest.log](https://github.com/TerraForged/tracker/files/6024938/latest.log)

**Comment by Won-Ton** [comment]
Can confirm the issue. Will be patched in the next update
