### ISSUE TITLE
Issue with TerraForged + BYG

### ISSUE THREAD

**Issue by NaomiKuroi** [TerraForged/tracker#64]
Discovered some interesting terrain generation with lakes while using both TerraForged 0.2.7 and Oh The Biomes You'll Go 1.1.10:

![2021-02-22_12 15 44](https://user-images.githubusercontent.com/47642944/108764875-fc1e5800-7507-11eb-8ac7-467b96d154be.png)
![2021-02-22_12 16 29](https://user-images.githubusercontent.com/47642944/108764890-ff194880-7507-11eb-8422-3a4a15cd7055.png)

I had no other mods installed when taking these screenshots.

**Comment by Won-Ton** [comment]
Looks like their surface generator stops at water level instead of going down

**Comment by NaomiKuroi** [comment]
Apologies if this is just stupidity on my end, but is it normal then for other land biomes to be able to generate on top of the lakes like that? I'm referring to the lakes that form at the end of the rivers. I guess I'll have to take a look and see if other mods like BOP do the same thing.
