### ISSUE TITLE
Trees not spawning for BYG biomes

### ISSUE THREAD

**Issue by MrMontes12** [TerraForged/tracker#67]
Using the latest versions of both mods, with no other mods installed, BYG biomes are generated in the world but with no trees.
Vanilla biomes generate normally.
![image](https://user-images.githubusercontent.com/48678533/108945524-daaca000-76b0-11eb-9478-4b1c5104a8e0.png)

**Comment by Won-Ton** [comment]
Hi, it has been reported, thanks. I've found some measures we can take to stop that happening which'll be included in the next release
