### ISSUE TITLE
Snow layers are see through

### ISSUE THREAD

**Issue by HopsandBarley** [TerraForged/tracker#69]
**PLEASE PROVIDE DETAILED INFORMATION, LOGS, CRASH-REPORTS.**  
[Search for existing issues before opening a new one.](https://github.com/TerraForged/tracker/issues?q=)  
_Note: we are not accepting feature requests/questions. Just bugs pls :]_

Playing on 1.16.5.  I spawned into a snow biome, and the vertical walls of much of the snow layers are not visible. 

It seems to happen when Terraforged and Ferritecore are both installed.

**Comment by Won-Ton** [comment]
Not 100% sure what you mean but 99.999% it has nothing to do with TerraForged. We have nothing to do with how blocks are rendered
