### ISSUE TITLE
Crash with YUNG's better caves 

### ISSUE THREAD

**Issue by BentoGambin** [TerraForged/tracker#7]
This actually has all the information needed, and you guys might have already even tracked it, but in case you didn't:
https://github.com/yungnickyoung/YUNGs-Better-Caves/issues/104
Btw thanks for ruining vanilla minecraft for me, now I can't play without your mod :(

**Comment by Won-Ton** [comment]
Thanks. Aware of it and have offered advice in that thread. Will leave this open incase others stop by.

**Comment by Won-Ton** [comment]
Should be resolved in bettercaves v1.1.1
