### ISSUE TITLE
Modded Structures Won't Spawn

### ISSUE THREAD

**Issue by brotherpk6** [TerraForged/tracker#70]
No idea if this is intentional, but modded structures from most mods don't spawn on a terraforged world.  Dungeons Plus, The Conjurer, and Better Mineshafts are ALL having this problem. Likely other mods that I don't use as well.

**Comment by Won-Ton** [comment]
Hi. TerraForged can only generate structures if the mod adding the structure(s) has properly registered their 'separation settings' for each of them (these tell the chunk generator how to space them out).

We have a section on our wiki with a brief guide for developers on how to do that which you could suggest to them. It's pretty easy to accommodate :)
https://github.com/TerraForged/TerraForged/wiki/Mod:-Structures:-Compatibility

**Comment by brotherpk6** [comment]
Makes sense and I appreciate the help! Now time to pass this to the devs of other mods :)

**Comment by zanecek** [comment]
Pls how I can added structures myself via datapack?
Thank you for the advice.

**Comment by Won-Ton** [comment]
> Pls how I can added structures myself via datapack?
> Thank you for the advice.

I added a wiki page and template datapack you can edit:
https://github.com/TerraForged/TerraForged/wiki/User:-Datapacks:-Structures

**Comment by zanecek** [comment]
Thank you. But template databack has bad link (error 404).

**Comment by Won-Ton** [comment]
Oops sorry the repo was private. It's pubic now :)

**Comment by zanecek** [comment]
Hi. Thanks.
I use mods with structures that worked well.
Do I have to add them to the datapack too?
[crash-2021-03-01_01.21.52-client.txt](https://github.com/TerraForged/tracker/files/6058490/crash-2021-03-01_01.21.52-client.txt)

**Comment by Won-Ton** [comment]
Shoudn't need to, no. That crash is unreletated. It isn't caused by TF
