### ISSUE TITLE
Can't make new world after latest update

### ISSUE THREAD

**Issue by AdnanuReeves** [TerraForged/tracker#71]
Latest forge, latest terraforged
https://paste.ubuntu.com/p/4qsCgqGk66/

Getting that when creating world with newest terraforged. Worked fine with the version before this one

**Comment by AdnanuReeves** [comment]
Well shit, looks like it's not the new version at fault but something else.. I don't understand what o.o

**Comment by AdnanuReeves** [comment]
https://www.curseforge.com/minecraft/mc-mods/shrines-structures
I believe this is the mod that caused it. Not sure if it's something I should report there instead?

**Comment by Won-Ton** [comment]
Hi. Can't tell. Maybe check your configs for those structures to make sure the seed values aren't negative first

**Comment by AdnanuReeves** [comment]
Ah I see. It is shrines then. Looked in the config and 2 of the structures are - seeds. I guess I'll ask the author how I can change that, if not I'll just disable those 2 I guess.
Thanks for the response :)

**Comment by Won-Ton** [comment]
Can you not just edit the config? The seed values can be any number between 0 and 2147483647. It doesn't matter what value, it's just used by a random number generator to randomise structure placement
