### ISSUE TITLE
Bugged Bamboo

### ISSUE THREAD

**Issue by alexanderkw** [TerraForged/tracker#77]
When Bamboo generates it seems to break and not break all at once - bamboo items are scattered around but bugged 'air' blocks remain. Trying to walk through reveals that the bamboo blocks are still around, but invisible and still impassible (attempting to walk into them can bug out slightly, but hitting at the air will break the unseen bamboo and drop the item).

I have observed this in various different combinations of mods, including those without modded biomes. The following image shows an example of Bamboo Jungle, taken in 1.16.5 with the most recent version of TF:

[https://i.imgur.com/4dcNJED](https://i.imgur.com/4dcNJED)

I can provide logs etc if required.

**Comment by Won-Ton** [comment]
That isn't caused by terraforged, that is a clientside/rendering bug. Bad block model/texture or something.
