### ISSUE TITLE
World stuck at loading screen after finishing 100% world generation (v0.1.3)

### ISSUE THREAD

**Issue by OrangeBurrito** [TerraForged/tracker#80]
Not sure if this is a bug or not, but when I create a new Terraforged world and change the sliders of:
Mountain
Rivers in general
Lakes
Spawn Vanilla Lakes, the world generates up to 100% and then shows the dirt loading screen.  When I check the logs on the side it says I joined the game and mod messages appear in the console but the loading screen does not change.

If this is any help I'm using MultiMC with about a hundred and sixty mods, but the terraforged world gen was working smoothly for a while before adding and removing the MCMT mod (I also did a full reinstall of MultiMC after that)
Logs (trimmed to exclude game launching)
Log1: https://pastebin.com/RG9Y7War
Log2: https://pastebin.com/UNVh9YyV

**Comment by Won-Ton** [comment]
Hi. Nothing in the logs to suggest TerraForged is the issue here. You'd have to do your own investigation of removing/adding mods to find the culprit
