### ISSUE TITLE
Fatal server crash on chunk load

### ISSUE THREAD

**Issue by rsslcs** [TerraForged/tracker#81]
[crash-2021-03-16_19.39.57-server.txt](https://github.com/TerraForged/tracker/files/6152074/crash-2021-03-16_19.39.57-server.txt)
[debug.log](https://github.com/TerraForged/tracker/files/6152076/debug.log)
[latest.log](https://github.com/TerraForged/tracker/files/6152077/latest.log)

Crash occurs whilst exploring overworld, generating new chunks.

**Comment by Won-Ton** [comment]
Hi. It's being caused by the geolosys mod
