### ISSUE TITLE
Crash with Repurposed Structures

### ISSUE THREAD

**Issue by Darkfiend009** [TerraForged/tracker#85]
Minecraft: 1.16.5
Forge: 36.1.0
Terraforged: 0.2.9

Crash Report: https://pastebin.com/E7m0kSzb

Client crashed while entering a single player world for the first time. I am also reporting this to the Repurposed Structure issue tracker just in case it's on that end.

**Comment by Won-Ton** [comment]
Hi, this is not caused by TerraForged. There looks to be a number of mods that could be the culprit listed in the stacktrace - I'd start from the top and work down
