### ISSUE TITLE
Vanilla trees in modded biomes don't use their respective Terraforged designs

### ISSUE THREAD

**Issue by Brun333rp** [TerraForged/tracker#87]
Trees in modded biomes will have their vanilla appearance, rather than their Terraforged designs.

![2021-03-24_17 04 36](https://user-images.githubusercontent.com/77504298/112379797-5822fa80-8cc7-11eb-9a3a-4eda1cd0296e.png)
![2021-03-24_17 03 04](https://user-images.githubusercontent.com/77504298/112379806-5a855480-8cc7-11eb-98aa-da4d4f445a53.png)

**Comment by Won-Ton** [comment]
Yep we don't modify other mods' stuff
