### ISSUE TITLE
Structures spawn in lakes/rivers

### ISSUE THREAD

**Issue by Suraru** [TerraForged/tracker#90]
**PLEASE PROVIDE DETAILED INFORMATION, LOGS, CRASH-REPORTS.**  
[Search for existing issues before opening a new one.](https://github.com/TerraForged/tracker/issues?q=)  
_Note: we are not accepting feature requests/questions. Just bugs pls :]_

Mods that add structures, like Astral Sorcery, Shrines, or Ice and Fire will generate them on top of rivers or lakes.

**Comment by Won-Ton** [comment]
The structure(s) in question decide where they place.
The vanilla structures allow themselves to place in water too.
