### ISSUE TITLE
Buildings from Mystical World are not generated

### ISSUE THREAD

**Issue by kellixon** [TerraForged/tracker#91]
1.16.5. TerraForged 0.2.9. Actually, the problem is in the name of the topic. 3 buildings are not generated from the MysticalWorld mod. This is written in my the log.

**Comment by Won-Ton** [comment]
TF can only use structures that have had their settings registered properly.

More info:
https://github.com/TerraForged/TerraForged/wiki/Mod:-Structures:-Compatibility
