### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by StrangerSon713** [TerraForged/tracker#92]
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 4/5/21 10:51 AM
Description: generating air carvers (TerraForged World-Gen)

java.lang.NullPointerException: generating air carvers (TerraForged World-Gen)
	at com.blackgear.bgcore.common.world.features.carver.NoiseCarver.func_225555_a_(NoiseCarver.java:114) ~[?:3.1.2] {re:classloading}
	at com.blackgear.bgcore.common.world.features.carver.NoiseCarver.func_225555_a_(NoiseCarver.java:29) ~[?:3.1.2] {re:classloading}
	at net.minecraft.world.gen.carver.ConfiguredCarver.func_227207_a_(SourceFile:39) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at com.terraforged.mod.chunk.generator.TerrainCarver.carve(TerrainCarver.java:101) ~[?:1.16.4-0.2.9] {re:classloading}
	at com.terraforged.mod.chunk.generator.TerrainCarver.carveTerrain(TerrainCarver.java:69) ~[?:1.16.4-0.2.9] {re:classloading}
	at com.terraforged.mod.chunk.TFChunkGenerator.func_230350_a_(TFChunkGenerator.java:228) ~[?:1.16.4-0.2.9] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.func_222590_c(ChunkStatus.java:66) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:ChunkStatusMixin,pl:mixin:APP:byg.mixins.json:common.world.ChunkStatusMixin,pl:mixin:A}
	at net.minecraft.world.chunk.ChunkStatus$ISelectiveWorker.doWork(ChunkStatus.java:240) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:ChunkStatusMixin,pl:mixin:APP:byg.mixins.json:common.world.ChunkStatusMixin,pl:mixin:A}
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {re:classloading,re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$scheduleChunkGeneration$20(ChunkManager.java:522) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_74] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_74] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_74] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) [?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) [?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) [?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) [?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_74] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Current Chunk --
Details:
	Pos: [36, 330]
	Status: surface
	Structure Starts: [iceandfire:graveyard, minecraft:mineshaft, minecraft:ruined_portal, minecraft:stronghold, quark:big_dungeon]
	Structure Refs: []

-- TerraForged ChunkGenerator --
Details:
	Seed: -57232267
	Settings: {"miscellaneous":{"smoothLayerDecorator":true,"strataRegionSize":600,"strataDecorator":true,"oreCompatibleStoneOnly":true,"erosionDecorator":true,"plainStoneErosion":false,"naturalSnowDecorator":true,"customBiomeFeatures":true,"vanillaLakes":false,"vanillaSprings":true,"vanillaLavaLakes":true,"vanillaLavaSprings":true,"mountainBiomeUsage":0.4,"volcanoBiomeUsage":0.4},"dimensions":{"bedrockLayer":{"material":"minecraft:bedrock","minDepth":1,"variance":4},"dimensions":{"nether":"default","end":"default","includeExtraDimensions":true}},"structures":{"stronghold":{"distance":32,"spread":3,"count":128,"salt":0,"constrainToBiomes":false,"disabled":false},"structures":{"atmospheric:arid_shrine":{"spacing":32,"separation":8,"salt":304972544,"disabled":false},"autumnity:maple_witch_hut":{"spacing":32,"separation":8,"salt":56181420,"disabled":false},"iceandfire:gorgon_temple":{"spacing":16,"separation":8,"salt":342226464,"disabled":false},"iceandfire:graveyard":{"spacing":48,"separation":24,"salt":342226432,"disabled":false},"iceandfire:mausoleum":{"spacing":30,"separation":15,"salt":342226464,"disabled":false},"minecraft:buried_treasure":{"spacing":1,"separation":0,"salt":0,"disabled":false},"minecraft:desert_pyramid":{"spacing":32,"separation":8,"salt":14357617,"disabled":false},"minecraft:igloo":{"spacing":32,"separation":8,"salt":14357618,"disabled":false},"minecraft:jungle_pyramid":{"spacing":32,"separation":8,"salt":14357619,"disabled":false},"minecraft:mansion":{"spacing":80,"separation":20,"salt":10387319,"disabled":false},"minecraft:mineshaft":{"spacing":1,"separation":0,"salt":0,"disabled":false},"minecraft:monument":{"spacing":32,"separation":5,"salt":10387313,"disabled":false},"minecraft:nether_fossil":{"spacing":2,"separation":1,"salt":14357921,"disabled":false},"minecraft:ocean_ruin":{"spacing":20,"separation":8,"salt":14357621,"disabled":false},"minecraft:pillager_outpost":{"spacing":32,"separation":8,"salt":165745296,"disabled":false},"minecraft:ruined_portal":{"spacing":40,"separation":15,"salt":34222644,"disabled":false},"minecraft:shipwreck":{"spacing":24,"separation":4,"salt":165745296,"disabled":false},"minecraft:swamp_hut":{"spacing":32,"separation":8,"salt":14357620,"disabled":false},"minecraft:village":{"spacing":32,"separation":8,"salt":10387312,"disabled":false},"quark:big_dungeon":{"spacing":20,"separation":11,"salt":79234824,"disabled":false}}},"world":{"continent":{"continentType":"MULTI","continentShape":"EUCLIDEAN","continentScale":3000,"continentJitter":0.7},"controlPoints":{"deepOcean":0.1,"shallowOcean":0.25,"beach":0.327,"coast":0.448,"inland":0.502},"properties":{"spawnType":"CONTINENT_CENTER","worldHeight":256,"seaLevel":63}},"climate":{"temperature":{"seedOffset":0,"scale":6,"falloff":2,"min":0.0,"max":0.98,"bias":0.05},"moisture":{"seedOffset":0,"scale":6,"falloff":1,"min":0.0,"max":1.0,"bias":0.0},"biomeShape":{"biomeSize":225,"macroNoiseSize":8,"biomeWarpScale":150,"biomeWarpStrength":80},"biomeEdgeShape":{"type":"SIMPLEX","scale":24,"octaves":2,"gain":0.5,"lacunarity":2.65,"strength":14}},"terrain":{"general":{"terrainSeedOffset":0,"terrainRegionSize":1200,"globalVerticalScale":0.98,"globalHorizontalScale":1.0,"fancyMountains":true},"steppe":{"weight":1.0,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"plains":{"weight":2.0,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"hills":{"weight":2.0,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"dales":{"weight":1.5,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"plateau":{"weight":1.5,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"badlands":{"weight":1.0,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"torridonian":{"weight":2.0,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"mountains":{"weight":2.5,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0},"volcano":{"weight":5.0,"baseScale":1.0,"verticalScale":1.0,"horizontalScale":1.0}},"rivers":{"seedOffset":0,"riverCount":8,"mainRivers":{"bedDepth":5,"minBankHeight":2,"maxBankHeight":6,"bedWidth":8,"bankWidth":20,"fade":0.75},"branchRivers":{"bedDepth":4,"minBankHeight":1,"maxBankHeight":4,"bedWidth":5,"bankWidth":14,"fade":0.975},"lakes":{"chance":0.3,"minStartDistance":0.0,"maxStartDistance":0.03,"depth":10,"sizeMin":75,"sizeMax":150,"minBankHeight":2,"maxBankHeight":10},"wetlands":{"chance":0.6,"sizeMin":175,"sizeMax":225}},"filters":{"erosion":{"dropletsPerChunk":135,"dropletLifetime":12,"dropletVolume":0.7,"dropletVelocity":0.7,"erosionRate":0.5,"depositeRate":0.5},"smoothing":{"iterations":1,"smoothingRadius":1.8,"smoothingRate":0.9}}}

-- TerraForged BiomeProvider --
Details:
	Overworld Biomes: [byg:allium_fields, biomesoplenty:alps, byg:alps, byg:amaranth_fields, byg:ancient_forest, byg:araucaria_forest, byg:araucaria_savanna, byg:aspen_clearing, byg:aspen_forest, byg:autumnal_valley, minecraft:badlands, minecraft:badlands_plateau, biomesoplenty:bamboo_blossom_grove, byg:bamboo_forest, minecraft:bamboo_jungle, byg:baobab_savanna, byg:basalt_barrera, biomesoplenty:bayou, byg:bayou, biomesoplenty:bayou_mangrove, minecraft:beach, minecraft:birch_forest, byg:black_forest_clearing, byg:blue_giant_taiga, byg:blue_taiga, byg:bluff_peaks, byg:bluff_steeps, byg:bog, byg:boreal_clearing, byg:boreal_forest, terraforged:bryce, biomesoplenty:burnt_forest, byg:canyon_edge, byg:canyons, byg:cherry_blossom_clearing, byg:cherry_blossom_forest, biomesoplenty:cherry_blossom_grove, byg:cika_mountains, byg:cika_woods, terraforged:cold_marshland, minecraft:cold_ocean, terraforged:cold_steppe, byg:cold_swamplands, byg:coniferous_clearing, biomesoplenty:coniferous_forest, byg:coniferous_forest, biomesoplenty:coniferous_lakes, byg:coral_mangroves, byg:crag_gardens, byg:cypress_swamplands, minecraft:dark_forest, biomesoplenty:dead_forest, byg:dead_sea, biomesoplenty:dead_swamp, byg:deciduous_clearing, byg:deciduous_forest, biomesoplenty:deep_bayou, minecraft:deep_cold_ocean, minecraft:deep_frozen_ocean, minecraft:deep_lukewarm_ocean, minecraft:deep_ocean, minecraft:deep_warm_ocean, minecraft:desert, minecraft:desert_lakes, byg:dover_mountains, biomesoplenty:dry_boneyard, biomesoplenty:dryland, byg:dummy, atmospheric:dunes, byg:dunes, byg:ebony_woods, byg:enchanted_forest, byg:enchanted_grove, minecraft:eroded_badlands, byg:evergreen_clearing, byg:evergreen_taiga, biomesoplenty:fir_clearing, terraforged:fir_forest, atmospheric:flourishing_dunes, minecraft:flower_forest, biomesoplenty:flower_meadow, terraforged:flower_plains, byg:flowering_ancient_forest, byg:flowering_enchanted_grove, byg:flowering_grove, byg:flowering_meadow, minecraft:forest, byg:forest_fault, byg:fresh_water_lake, byg:frozen_lake, terraforged:frozen_lake, terraforged:frozen_marsh, minecraft:frozen_ocean, minecraft:frozen_river, biomesoplenty:fungal_field, biomesoplenty:fungal_jungle, byg:fungal_patch, minecraft:giant_spruce_taiga, minecraft:giant_tree_taiga, byg:glowing_ancient_forest, byg:glowshroom_bayou, biomesoplenty:golden_prairie, byg:grassland_plateau, biomesoplenty:gravel_beach, minecraft:gravelly_mountains, byg:great_lake_isles, byg:great_lakes, biomesoplenty:grove, byg:grove, biomesoplenty:grove_clearing, biomesoplenty:grove_lakes, byg:guiana_clearing, byg:guiana_shield, biomesoplenty:highland, biomesoplenty:highland_crag, biomesoplenty:highland_moor, minecraft:ice_spikes, byg:jacaranda_clearing, byg:jacaranda_forest, biomesoplenty:jade_cliffs, biomesoplenty:jade_grassland, minecraft:jungle, minecraft:jungle_edge, terraforged:lake, biomesoplenty:lavender_field, biomesoplenty:lavender_forest, minecraft:lukewarm_ocean, biomesoplenty:lush_desert, byg:lush_red_desert, biomesoplenty:lush_savanna, byg:lush_tundra, byg:mangrove_marshes, autumnity:maple_forest, byg:maple_taiga, terraforged:marshland, byg:marshlands, biomesoplenty:meadow, byg:meadow, biomesoplenty:meadow_forest, minecraft:modified_badlands_plateau, minecraft:modified_gravelly_mountains, minecraft:modified_jungle, minecraft:modified_jungle_edge, minecraft:modified_wooded_badlands_plateau, byg:mojave_desert, minecraft:mountains, minecraft:mushroom_field_shore, minecraft:mushroom_fields, biomesoplenty:mystic_grove, biomesoplenty:mystic_plains, byg:northern_forest, byg:oasis, minecraft:ocean, biomesoplenty:ominous_mire, biomesoplenty:ominous_woods, autumnity:orange_spotted_dark_forest, biomesoplenty:orchard, byg:orchard, biomesoplenty:overgrown_fungal_jungle, atmospheric:petrified_dunes, minecraft:plains, byg:pointed_stone_forest, byg:polluted_lake, biomesoplenty:prairie, byg:prairie, byg:prairie_clearing, autumnity:pumpkin_fields, byg:pumpkin_forest, byg:rainbow_beach, atmospheric:rainforest, biomesoplenty:rainforest, atmospheric:rainforest_basin, biomesoplenty:rainforest_cliffs, biomesoplenty:rainforest_floodplain, atmospheric:rainforest_mountains, atmospheric:rainforest_plateau, byg:red_desert, byg:red_desert_dunes, byg:red_oak_forest, byg:red_rock_highlands, byg:red_rock_lowlands, byg:red_rock_mountains, autumnity:red_spotted_taiga, byg:red_spruce_taiga, byg:redwood_clearing, biomesoplenty:redwood_forest, biomesoplenty:redwood_forest_edge, byg:redwood_mountains, byg:redwood_tropics, minecraft:river, byg:rocky_beach, atmospheric:rocky_dunes, byg:rose_fields, minecraft:savanna, minecraft:savanna_plateau, terraforged:savanna_scrub, biomesoplenty:scrubland, byg:seasonal_birch_forest, byg:seasonal_deciduous_clearing, byg:seasonal_deciduous_forest, biomesoplenty:seasonal_forest, byg:seasonal_forest, byg:seasonal_giant_taiga, biomesoplenty:seasonal_orchard, biomesoplenty:seasonal_pumpkin_patch, byg:seasonal_taiga, byg:shattered_glacier, minecraft:shattered_savanna, minecraft:shattered_savanna_plateau, terraforged:shattered_savanna_scrub, biomesoplenty:shrubland, byg:shrublands, byg:sierra_range, byg:sierra_valley, biomesoplenty:silkglade, biomesoplenty:silkglade_nest, byg:skyris_highlands, byg:skyris_highlands_clearing, byg:skyris_peaks, byg:skyris_steeps, minecraft:snowy_beach, byg:snowy_black_beach, byg:snowy_blue_giant_taiga, byg:snowy_blue_taiga, byg:snowy_coniferous_clearing, biomesoplenty:snowy_coniferous_forest, byg:snowy_coniferous_forest, byg:snowy_deciduous_clearing, byg:snowy_deciduous_forest, byg:snowy_evergreen_clearing, byg:snowy_evergreen_taiga, biomesoplenty:snowy_fir_clearing, terraforged:snowy_fir_forest, biomesoplenty:snowy_maple_forest, minecraft:snowy_mountains, byg:snowy_rocky_black_beach, minecraft:snowy_taiga, minecraft:snowy_taiga_mountains, minecraft:snowy_tundra, atmospheric:sparse_rainforest_basin, atmospheric:sparse_rainforest_plateau, terraforged:steppe, byg:stone_forest, terraforged:stone_forest, minecraft:stone_shore, minecraft:sunflower_plains, minecraft:swamp, minecraft:taiga, minecraft:taiga_mountains, terraforged:taiga_scrub, minecraft:tall_birch_forest, byg:the_black_forest, biomesoplenty:tropic_beach, byg:tropical_fungal_forest, byg:tropical_islands, byg:tropical_rainforest, biomesoplenty:tundra, biomesoplenty:tundra_basin, biomesoplenty:tundra_bog, byg:twilight_valley, byg:vibrant_swamplands, biomesoplenty:volcano, terraforged:warm_beach, minecraft:warm_ocean, biomesoplenty:wasteland, byg:weeping_witch_clearing, byg:weeping_witch_forest, biomesoplenty:wetland, biomesoplenty:wetland_marsh, byg:white_beach, minecraft:wooded_badlands_plateau, byg:wooded_grassland_plateau, byg:wooded_meadow, minecraft:wooded_mountains, byg:wooded_red_rock_mountains, biomesoplenty:wooded_scrubland, biomesoplenty:wooded_wasteland, byg:woodlands, autumnity:yellow_spotted_forest, byg:zelkova_clearing, byg:zelkova_forest]

-- TerraForged Performance Config --
Details:
	version: 1.1
	thread_count: 8
	tile_size: 3
	batching: true
	batch_count: 6

-- TerraForged Biome Weights Config --
Details:
	terraforged:example_biome: 10

-- TerraForged Profiler --
Details:
	Timings: 
		Section             Count      Time MS    Min MS     Max MS     Average MS
		structure_starts    529        4486       0          4401       8.48
		structure_refs      46         21         0          0          0.46
		biomes              9          831        0          824        92.33
		terrain             3          138        17         91         46.00
		surface             1          29         29         29         29.00
		air_carvers         1          407        407        407        407.00
		fluid_carvers       0          0          0          0          0.00
		decoration          0          0          0          0          0.00
		mob_spawns          0          0          0          0          0.00
		Sum                                                             583.27

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Mac OS X (x86_64) version 10.14.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1676629368 bytes (1598 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 8
	JVM Flags: 8 total; -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.2.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.2.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.2.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.2.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.2.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.2
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.2-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		tetra-1.16.5-3.8.0.jar                            |Tetra                         |tetra                         |3.8.0               |DONE      |NOSIGNATURE
		QuarkOddities-1.16.3.jar                          |Quark Oddities                |quarkoddities                 |1.16.3              |DONE      |NOSIGNATURE
		theoneprobe-1.16-3.0.7.jar                        |The One Probe                 |theoneprobe                   |1.16-3.0.7          |DONE      |NOSIGNATURE
		BiomesOPlenty-1.16.4-13.0.0.432-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.432   |DONE      |NOSIGNATURE
		infernal-expansion-forge-1.3.jar                  |Infernal Expansion            |infernalexp                   |Release 1.3         |DONE      |NOSIGNATURE
		PreGenForge-0.2.2-mc1.16.4.jar                    |PreGenForge                   |pregenforge                   |0.2.2               |DONE      |NOSIGNATURE
		jei-1.16.5-7.6.1.75.jar                           |Just Enough Items             |jei                           |7.6.1.75            |DONE      |NOSIGNATURE
		abnormals_core-1.16.5-3.1.1.jar                   |Abnormals Core                |abnormals_core                |3.1.1               |DONE      |NOSIGNATURE
		buzzier_bees-1.16.5-3.0.1.jar                     |Buzzier Bees                  |buzzier_bees                  |3.0.1               |DONE      |NOSIGNATURE
		berry_good-1.16.5-4.1.1.jar                       |Berry Good                    |berry_good                    |4.1.1               |DONE      |NOSIGNATURE
		DarkerDepths-1.16.5-1.0.1.jar                     |Darker Depths                 |darkerdepths                  |1.0.1}              |DONE      |NOSIGNATURE
		atmospheric-1.16.5-3.1.0.jar                      |Atmospheric                   |atmospheric                   |3.1.0               |DONE      |NOSIGNATURE
		upgrade_aquatic-1.16.5-3.1.0.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.1.0               |DONE      |NOSIGNATURE
		savageandravage-1.16.5-3.1.0.jar                  |Savage & Ravage               |savageandravage               |3.1.0               |DONE      |NOSIGNATURE
		Patchouli-1.16.4-50.jar                           |Patchouli                     |patchouli                     |1.16.4-50           |DONE      |NOSIGNATURE
		create-mc1.16.3_v0.3e.jar                         |Create                        |create                        |mc1.16.3_v0.3e      |DONE      |NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.1.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.1        |DONE      |NOSIGNATURE
		TerraForged-1.16.4-0.2.9.jar                      |TerraForged                   |terraforged                   |0.2.9               |DONE      |7b:73:d0:a2:c3:40:13:84:35:4f:c9:0e:2b:85:8c:08:ea:3c:3c:eb:f1:98:8b:5b:6e:ca:8a:a0:9a:cf:12:b3
		mgui-1.16.4-3.1.3.jar                             |mgui                          |mgui                          |3.1.3               |DONE      |NOSIGNATURE
		Controlling-7.0.0.14.jar                          |Controlling                   |controlling                   |7.0.0.14            |DONE      |NOSIGNATURE
		autumnity-1.16.5-2.1.0.jar                        |Autumnity                     |autumnity                     |2.1.0               |DONE      |NOSIGNATURE
		comforts-forge-1.16.4-4.0.1.0.jar                 |Comforts                      |comforts                      |1.16.4-4.0.1.0      |DONE      |NOSIGNATURE
		citadel-1.6.2.jar                                 |Citadel                       |citadel                       |1.6.2               |DONE      |NOSIGNATURE
		alexsmobs-1.8.1.jar                               |Alex's Mobs                   |alexsmobs                     |1.8.1               |DONE      |NOSIGNATURE
		rats-7.1.1-1.16.5.jar                             |Rats                          |rats                          |7.1.1               |DONE      |NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |DONE      |NOSIGNATURE
		YungsApi-1.16.4-Forge-4.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-4      |DONE      |NOSIGNATURE
		tombstone-1.16-6.3.3.jar                          |Corail Tombstone              |tombstone                     |6.3.3               |DONE      |NOSIGNATURE
		structurize-0.13.160-ALPHA-universal.jar          |Structurize                   |structurize                   |0.13.160-ALPHA      |DONE      |NOSIGNATURE
		minecolonies-0.14.83-ALPHA-universal.jar          |MineColonies                  |minecolonies                  |0.14.83-ALPHA       |DONE      |NOSIGNATURE
		iceandfire-2.1.6-1.16.4.jar                       |Ice and Fire                  |iceandfire                    |2.1.6-1.16.4        |DONE      |NOSIGNATURE
		byg-1.1.14.jar                                    |Oh The Biomes You'll Go       |byg                           |1.1.14              |DONE      |NOSIGNATURE
		bgcore-1.16.5-3.1.2.jar                           |bgcore                        |bgcore                        |3.1.2               |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.2-universal.jar                 |Forge                         |forge                         |36.1.2              |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Quark-r2.4-309.jar                                |Quark                         |quark                         |r2.4-309            |DONE      |NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |DONE      |NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |DONE      |NOSIGNATURE
		ratlantis-1.0.0-1.16.3.jar                        |Rats: Ratlantis               |ratlantis                     |1.0.0-1.16.3        |DONE      |NOSIGNATURE
	Crash Report UUID: e976ed8a-529b-49ee-bc54-dafa85638d85
	Patchouli open book context: n/a

**Comment by Won-Ton** [comment]
See the reply here: https://github.com/ItsBlackGear/bgcore/issues/1

Apparently bgcore is designed quite strictly to only run only with default/vanilla world-gen so it cannot be used alongside TerraForged or other world-generators like it.

You'd have to disable its world-gen features if it offers that in their configs
