### ISSUE TITLE
World stops loading / generating

### ISSUE THREAD

**Issue by Darianna77** [TerraForged/tracker#95]
I have big problems with the mod. When i make a new world with the terraforged generation i can walk only a few chunks / blocks before it stops the generation / loading and ill look on emptyness. it wont load more when i wait...when i restart the game i can get one chunk more or so, sometimes it wont. Have tried it in 3 different Modpacks to make sure it isnt something in the specially pack. In all packs the same problems. Have ask for help in the Pack Discord from the Pack what i want to play. The dont know whats wrong. In the performance config i have changed the thread count to 6 from 10. It havent help.

Cant use this mod, and Enigmatica 6 uses this worldgen as Default so all the features and so on are only there. And yeah it looks freaking good on pictures :( 

Any hints whats wrong here and what i could try?
I am playing always singleplayer. Use an i5 7600k CPU, an Nvidia 1070 GPU. Have 16 GB Ram in total and the Packs get 6 GB.

**Comment by Won-Ton** [comment]
This is usually caused by a poorly written structure or entity that has deadlocked the server.

Reproduce the issue and wait for a minute or so. The game should detect that you have deadlocked and crash itself - the crash report will provide invaluable information as to what has gone wrong.

**Comment by Darianna77** [comment]
Mhh no...i have wait way more then 1 Minute and nothing happens...no crash but also no more generation. It happens on All worlds that i generate....in 3 different modpacks with different mods in and so on

**Comment by Won-Ton** [comment]
Debug logs then? 

+ You can also force a crash by holding `F3+C` for like 15 seconds (it counts down in chat)

+ Have you reproduced with just TF installed?

**Comment by Darianna77** [comment]
Sorry for not responding, im ill in moment. I have tried it with only TF yeah. That seems to work but i want to play modded so it wont help me ;)  I can give you a latest.log . 
When i dont use a texturepack and not Jouneymap as a map mod i can explore further but then at some point the server isnt respondig and i must kill the process. These force a crahs i dont have try ( didnt know that)

Oh and to make that clear...i dont say , or think TF is buggy here, that this is caused from a bug. I hava only hoped that someone has these problerms too and can help me to tinker around in the configs or so. I think its an performance thing or so But my PC isnt that bad and so i dont understand it :) Many other peoplys can play E6 (thats the pack what i want to play) Pack with the TF generation just fine..so it cant be a bug or so

**Comment by Won-Ton** [comment]
You need to report to the modpack devs as it's on them to test that the mods they add work together and support their users. I'm confident the cause of the hangs is not TF - if the modpack devs can demonstrate that it is with data/logs/reports, then they can provide that information to me and I can start fixing it.
