### ISSUE TITLE
Terraforged  0.29 crashes when clicking on customise world creation.

### ISSUE THREAD

**Issue by Cr4fTJuNkiE** [TerraForged/tracker#96]
[crash-2021-04-13_18.18.00-client.txt](https://github.com/TerraForged/tracker/files/6307045/crash-2021-04-13_18.18.00-client.txt)

Crashes every time I try to create a new Terraforged world in 1.16.5.

**Comment by Won-Ton** [comment]
One (or more) of the structures you have installed is configured incorrectly and has a negative seed assigned to it. Likely a another mod, but could be a misconfigured datapack too.
