### ISSUE TITLE
Mushroom Island Pillars

### ISSUE THREAD

**Issue by Smilodonter** [TerraForged/tracker#97]
I noticed some funky generation between the mushroom biome and warm oceans. I don't think that these pillars are intentional.
![2021-04-15_15 51 42](https://user-images.githubusercontent.com/73894463/114881985-c6109c80-9e03-11eb-81bd-d2f5ed75da53.png)
![2021-04-15_15 51 26](https://user-images.githubusercontent.com/73894463/114882058-d6c11280-9e03-11eb-9b20-57cd0504a256.png)

**Comment by Won-Ton** [comment]
Can you provide the seed, generator settings (if custom) and coordinates please?

**Comment by Smilodonter** [comment]
{
  "bonus_chest": true,
  "dimensions": {
    "minecraft:overworld": {
      "type": "minecraft:overworld",
      "generator": {
        "type": "terraforged:generator",
        "value": {
          "biome_provider": {
            "seed": 1584644419,
            "game_data": {},
            "generator_settings": {
              "miscellaneous": {
                "smoothLayerDecorator": true,
                "strataRegionSize": 721,
                "strataDecorator": true,
                "oreCompatibleStoneOnly": true,
                "erosionDecorator": true,
                "plainStoneErosion": false,
                "naturalSnowDecorator": true,
                "customBiomeFeatures": true,
                "vanillaLakes": false,
                "vanillaSprings": true,
                "vanillaLavaLakes": true,
                "vanillaLavaSprings": false,
                "mountainBiomeUsage": 0.902,
                "volcanoBiomeUsage": 0.945
              },
              "dimensions": {
                "bedrockLayer": {
                  "material": "minecraft:bedrock",
                  "minDepth": 1,
                  "variance": 4
                },
                "dimensions": {
                  "nether": "default",
                  "end": "default",
                  "includeExtraDimensions": true
                }
              },
              "structures": {
                "stronghold": {
                  "distance": 32,
                  "spread": 3,
                  "count": 128,
                  "salt": 0,
                  "disabled": false
                },
                "structures": {
                  "minecraft:buried_treasure": {
                    "spacing": 1,
                    "separation": 0,
                    "salt": 0,
                    "disabled": false
                  },
                  "minecraft:desert_pyramid": {
                    "spacing": 32,
                    "separation": 8,
                    "salt": 14357617,
                    "disabled": false
                  },
                  "minecraft:igloo": {
                    "spacing": 32,
                    "separation": 8,
                    "salt": 14357618,
                    "disabled": false
                  },
                  "minecraft:jungle_pyramid": {
                    "spacing": 32,
                    "separation": 8,
                    "salt": 14357619,
                    "disabled": false
                  },
                  "minecraft:mansion": {
                    "spacing": 80,
                    "separation": 20,
                    "salt": 10387319,
                    "disabled": false
                  },
                  "minecraft:mineshaft": {
                    "spacing": 1,
                    "separation": 0,
                    "salt": 0,
                    "disabled": false
                  },
                  "minecraft:monument": {
                    "spacing": 32,
                    "separation": 5,
                    "salt": 10387313,
                    "disabled": false
                  },
                  "minecraft:ocean_ruin": {
                    "spacing": 20,
                    "separation": 8,
                    "salt": 14357621,
                    "disabled": false
                  },
                  "minecraft:pillager_outpost": {
                    "spacing": 32,
                    "separation": 8,
                    "salt": 165745296,
                    "disabled": false
                  },
                  "minecraft:ruined_portal": {
                    "spacing": 40,
                    "separation": 15,
                    "salt": 34222645,
                    "disabled": false
                  },
                  "minecraft:shipwreck": {
                    "spacing": 24,
                    "separation": 4,
                    "salt": 165745295,
                    "disabled": false
                  },
                  "minecraft:swamp_hut": {
                    "spacing": 32,
                    "separation": 8,
                    "salt": 14357620,
                    "disabled": false
                  },
                  "minecraft:village": {
                    "spacing": 32,
                    "separation": 8,
                    "salt": 10387312,
                    "disabled": false
                  }
                }
              },
              "world": {
                "continent": {
                  "continentType": "MULTI",
                  "continentShape": "EUCLIDEAN",
                  "continentScale": 4029,
                  "continentJitter": 0.8
                },
                "controlPoints": {
                  "deepOcean": 0.1,
                  "shallowOcean": 0.25,
                  "beach": 0.326,
                  "coast": 0.448,
                  "inland": 0.5
                },
                "properties": {
                  "spawnType": "CONTINENT_CENTER",
                  "worldHeight": 256,
                  "seaLevel": 63
                }
              },
              "climate": {
                "temperature": {
                  "seedOffset": 0,
                  "scale": 4,
                  "falloff": 2,
                  "min": 0.0,
                  "max": 1.0,
                  "bias": 0.097
                },
                "moisture": {
                  "seedOffset": 0,
                  "scale": 3,
                  "falloff": 1,
                  "min": 0.0,
                  "max": 1.0,
                  "bias": 0.0
                },
                "biomeShape": {
                  "biomeSize": 402,
                  "macroNoiseSize": 5,
                  "biomeWarpScale": 180,
                  "biomeWarpStrength": 110
                },
                "biomeEdgeShape": {
                  "type": "PERLIN2",
                  "scale": 14,
                  "octaves": 1,
                  "gain": 0.5,
                  "lacunarity": 2.65,
                  "strength": 60
                }
              },
              "terrain": {
                "general": {
                  "terrainSeedOffset": 0,
                  "terrainRegionSize": 1507,
                  "globalVerticalScale": 1.0,
                  "globalHorizontalScale": 1.175,
                  "fancyMountains": true
                },
                "steppe": {
                  "weight": 1.0,
                  "baseScale": 1.0,
                  "verticalScale": 1.0,
                  "horizontalScale": 1.0
                },
                "plains": {
                  "weight": 2.0,
                  "baseScale": 1.0,
                  "verticalScale": 1.0,
                  "horizontalScale": 1.0
                },
                "hills": {
                  "weight": 2.0,
                  "baseScale": 1.0,
                  "verticalScale": 1.0,
                  "horizontalScale": 1.0
                },
                "dales": {
                  "weight": 1.5,
                  "baseScale": 1.0,
                  "verticalScale": 1.0,
                  "horizontalScale": 1.0
                },
                "plateau": {
                  "weight": 1.5,
                  "baseScale": 1.0,
                  "verticalScale": 1.0,
                  "horizontalScale": 1.0
                },
                "badlands": {
                  "weight": 1.0,
                  "baseScale": 1.0,
                  "verticalScale": 1.0,
                  "horizontalScale": 1.0
                },
                "torridonian": {
                  "weight": 2.0,
                  "baseScale": 1.0,
                  "verticalScale": 1.0,
                  "horizontalScale": 1.0
                },
                "mountains": {
                  "weight": 2.5,
                  "baseScale": 1.0,
                  "verticalScale": 1.0,
                  "horizontalScale": 1.0
                },
                "volcano": {
                  "weight": 5.0,
                  "baseScale": 1.0,
                  "verticalScale": 1.0,
                  "horizontalScale": 1.0
                }
              },
              "rivers": {
                "seedOffset": 0,
                "riverCount": 13,
                "mainRivers": {
                  "bedDepth": 5,
                  "minBankHeight": 1,
                  "maxBankHeight": 5,
                  "bedWidth": 9,
                  "bankWidth": 28,
                  "fade": 0.27
                },
                "branchRivers": {
                  "bedDepth": 3,
                  "minBankHeight": 1,
                  "maxBankHeight": 3,
                  "bedWidth": 3,
                  "bankWidth": 18,
                  "fade": 0.7
                },
                "lakes": {
                  "chance": 0.595,
                  "minStartDistance": 0.0,
                  "maxStartDistance": 0.028,
                  "depth": 10,
                  "sizeMin": 75,
                  "sizeMax": 150,
                  "minBankHeight": 2,
                  "maxBankHeight": 10
                },
                "wetlands": {
                  "chance": 0.86,
                  "sizeMin": 175,
                  "sizeMax": 225
                }
              },
              "filters": {
                "erosion": {
                  "dropletsPerChunk": 165,
                  "dropletLifetime": 15,
                  "dropletVolume": 0.612,
                  "dropletVelocity": 0.652,
                  "erosionRate": 0.5,
                  "depositeRate": 0.5
                },
                "smoothing": {
                  "iterations": 1,
                  "smoothingRadius": 1.799,
                  "smoothingRate": 0.898
                }
              }
            }
          },
          "dimension_settings": "minecraft:overworld"
        }
      }
    },
    "minecraft:the_nether": {
      "type": "minecraft:the_nether",
      "generator": {
        "biome_source": {
          "preset": "minecraft:nether",
          "seed": 1584644419,
          "type": "minecraft:multi_noise"
        },
        "seed": 1584644419,
        "settings": "minecraft:nether",
        "type": "minecraft:noise"
      }
    },
    "minecraft:the_end": {
      "type": "minecraft:the_end",
      "generator": {
        "biome_source": {
          "seed": 1584644419,
          "type": "minecraft:the_end"
        },
        "seed": 1584644419,
        "settings": "minecraft:end",
        "type": "minecraft:noise"
      }
    }
  },
  "seed": 1584644419,
  "generate_features": true
}



Seed above! Coords: 4894 63 1472

**Comment by Won-Ton** [comment]
Ahh ok, it looks to be that one of TF's stone forest biomes is trying to generate there but the area has been upgraded to the mushroom, except at a few block positions.

 (The stone forest biome places some tall stone spires which is what you're seeing one column of)

I'll try figure out why it's missing a positions

**Comment by Won-Ton** [comment]
Hopefully fixed in 0.2.10
