### ISSUE TITLE
Crash when hitting "customize" option for terraforged world type

### ISSUE THREAD

**Issue by Gavin456b** [TerraForged/tracker#99]
As the title says, the game crashes instantly when trying to press the customize button. I do have quite a few mods installed but I am able to create a world just fine.

[crash-2021-04-18_19.42.05-client.txt](https://github.com/TerraForged/tracker/files/6332569/crash-2021-04-18_19.42.05-client.txt)

**Comment by Won-Ton** [comment]
One of your other mods' (or datapack's) structures is configured incorrectly - I can't tell which one unfortunately, you'll have to figure that out.

Looks to be either the "separation" or "spacing" setting for the structure is set to -1 which is causing minecraft to crash.
